.\" 1999 PTM Przemek Borys :-Q
.\" rpm - Red Hat Package Manager
.TH rpm 8 "22 Grudnia 1998" "Red Hat Software" "Red Hat Linux"
.SH NAZWA
rpm \- Mened¿er pakietów Red Hat
.SH SK£ADNIA
\fBrpm\fP [opcje] 
.SH OPIS
\fBrpm\fP jest potê¿nym \fImened¿erem pakietów\fR, który mo¿e byæ u¿ywany do
budowania, instalowania, zapytywania, weryfikowania, od¶wie¿ania i
odinstalowywania pakietów oprogramowania. Pakiet sk³ada siê z archiwum
plików oraz informacji pakietowej, takiej jak nazwa, wersja i opis.

Nale¿y wybraæ jeden z nastêpuj±cych podstawowych trybów:
\fIInicjalizowania bazy danych\fP, \fIPrzebudowywania bazy danych\fP,
\fIBudowania pakietu\fP, \fIRekompilowania pakietu\fP, \fIBudowania pakietu
z tarballa\fP, \fIZapytywania\fP, \fIPokazywania tagów zapytywania\fP,
\fIInstalowania\fP, \fIOd¶wie¿ania\fP, \fIOdinstalowywania\fP,
\fIWeryfikowania\fP, \fISprawdzania sygnatury\fP, \fIPonownego podpisywania\fP, 
\fIDodawania sygnatury\fP, \fIustawiania w³a¶cicieli i grup \fR oraz
\fIPokazywania konfiguracji\fP.



Obs³uga bazy danych:
.br
.I "\fB    rpm \-i [\-\-initdb]\fP"
.br
.I "\fB    rpm \-i [\-\-rebuilddb]\fP"

Budowanie:
.br
.I "\fB    rpm [\-b|t] [spec_pakietu]+\fP"
.br
.I "\fB    rpm [\-\-rebuild] [¼ród³owyrpm]+\fP"
.br
.I "\fB    rpm [\-\-tarbuild] [¼ród³owtar]+\fP"
.br

Querying:
.br
.I "\fB    rpm [\-\-query] [opcjezapytania]\fP"
.br
.I "\fB    rpm [\-\-querytags]\fP"
.br

Obs³uga zainstalowanych pakietów:
.br
.I "\fB    rpm [\-\-install] [opcjeinstalowania] [plik_pakietu]+\fP"
.br
.I "\fB    rpm [\-\-freshen|\-F] [opcjeinstalowania] [plik_pakietu]+\fP"
.br
.I "\fB    rpm [\-\-uninstall|\-e] [opcjeodinstalowania] [pakiet]+\fP"
.br
.I "\fB    rpm [\-\-verify|\-V] [opcjeweryfikowania] [pakiet]+\fP"
.br

Sygnatury:
.br
.I "\fB    rpm [\-\-verify|\-V] [opcjeweryfikowania] [pakiet]+\fP"
.br
.I "\fB    rpm [\-\-resign] [plik_z_pakietem]+\fP"
.br
.I "\fB    rpm [\-\-addsign] [plik_z_pakietem]+\fP"
.br

Ró¿ne:
.br
.I "\fB    rpm [\-\-showrc]\fP"
.br
.I "\fB    rpm [\-\-setperms] [pakiet]+\fP"
.br
.I "\fB    rpm [\-\-setgids] [pakiet]+\fP"
.br


.SH OPCJE OGÓLNE
Opcje te mog± byæ u¿ywane we wszystkich trybach.
.IP "\fB\-vv\fP"
Drukuje du¿o danych debuggowych.
.IP "\fB\-\-quiet\fP"
Drukuje jak najmniej \- zazwyczaj tylko komunikaty o b³êdach.
.IP "\fB\-\-help\fP"
Drukuje informacjê o u¿yciu d³u¿sz± ni¿ normalnie.
.IP "\fB\-\-version\fP"
Drukuje pojedyncz± liniê, zawieraj±c± numer wersji \fBrpm\fP.
.IP "\fB\-\-rcfile \fI<listaplików>\fP"
Ka¿dy z plików w oddzielonej dwukropkami \fI<li¶cieplików>\fP jest
odczytywany kolejno przez \fBrpm\fP w poszukiwnaiu informacji o
konfiguracji. Domy¶ln± \fI<list±plików\fP jest 
\fB/usr/lib/rpm/rpmrc:/etc/rpmrc:~/.rpmrc\fP.
Istnieæ musi tylko pierwszy plik listy, a tyldy bêd± rozszerzane na warto¶æ
\fB$HOME\fP.
.IP "\fB\-\-root \fI<katalog>\fP"
U¿yj do wszystkich operacji systemu zakorzenionego w \fI<katalogu>\fP.
Zauwa¿, ¿e oznacza to ¿e baza danych bêdzie odczytywana w \fI<katalogu>\fP,
a wszystkie skrypty \fIprzed\fP i \fIpo\fP bêd± uruchamiane po chroot(2) na
\fI<dir>\fP.
.IP "\fB\-\-dbpath \fI<¶cie¿ka>\fP"
U¿yj bazy danych rpm ze \fI<¶cie¿ki>\fP.
.IP "\fB\-\-justdb\fP"
Od¶wie¿ tylko bazê danych, nie system plików.
.IP "\fB\-\-ftpproxy \fI<host>\fP, \fB\-\-httpproxy \fI<host>\fP"
U¿yj \fI<hosta>\fP jako proxy FTP lub HTTP.
Zobacz \fBOPCJE FTP/HTTP\fP.
.IP "\fB\-\-ftpport \fI<port>\fP, \fB\-\-httpport \fI<port>\fP"
U¿yj \fI<portu>\fP jako portu FTP lub HTTP na ho¶cie proxy.
Zobacz \fBOPCJE FTP/HTTP\fP.
.IP "\fB\-\-pipe \fI<kmd>\fP"
Przekazuje potokiem wyj¶cie \fBrpm\fP do komendy \fI<kmd>\fP.

.SH OPCJE INSTALOWANIA I OD¦WIE¯ANIA
Ogóln± postaci± komendy instalowania rpm jest
.PP
	\fBrpm \-i [opcje-instalownaia] \fI<plik_pakietu>+\fP
.PP
Instaluje to nowy pakiet.
Ogoln± postaci± komendy od¶wie¿ania rpm jest
.PP
	\fBrpm \-U [opcje-instalowania] \fI<plik_pakietu>+\fP
.PP
Od¶wie¿a to lub instaluje pakiet na wersjê, obecn± w nowym RPM. Jest to to
samo co install, lecz wszystkie inne wersje pakietu bêda najpierw z systemu
usuwane.
.PP
	\fBrpm [\-F|--freshen] [opcje-instalowania] \fI<plik_pakietu>+\fP
.PP
Od¶wie¿y to pakiety, lecz tylko je¶li wcze¶niejsza wersja ju¿ istnieje.


\fI<plik_pakietu>\fP mo¿e byæ podany jako URL ftp lub http. W tym wypadku
pakiet zostanie pobrany przed zainstalowaniem . Zobacz \fBOPCJE FTP/HTTP\fR.
.PP
.IP "\fB\-\-force\fP"
To samo co u¿ycie \fB\-\-replacepkgs\fP, \fB\-\-replacefiles\fP, i
\fB\-\-oldpackage\fP.
.IP "\fB\-h\fP, \fB\-\-hash\fP"
Drukuje 50 znaków krzy¿yka, pokazuj±c proces rozpakowywania archiwum.
U¿ywaj±c z \fB\-v\fP, uzyskasz ³adny obraz.
.IP "\fB\-\-oldpackage\fP"
Zezwól od¶wie¿eniu na zast±pienie nowszego pakietu starszym.
.IP "\fB\-\-percent\fP"
Drukuj procenty podczas rozpoakowywania plików  z archiwum. Jest to zrobione
w celu u³atwienia wywo³ywnaia RPM z innych narzêdzi.
.IP "\fB\-\-replacefiles\fP"
Instaluj pakiety nawet je¶li zastêpuj± one pliki z innych, ju¿
zainstalowanych pakietów.
.IP "\fB\-\-replacepkgs\fP"
Instaluj pakiety nawet je¶li niektóre z nich s± ju¿ zainstalowane na tym
systemie.
.IP "\fB\-\-allfiles\fP"
Instaluje lub od¶wie¿a wszystkie brakuj±ceok (missingok) pliki z pakietu, 
niezale¿nie czy istniej±.
.IP "\fB\-\-nodeps\fP"
Nie dokonuj sprawdzenia zale¿no¶ci przed instalowaniem, lub od¶wie¿aniem
pakietu.
.IP "\fB\-\-noscripts\fP"
Nie wywo³uj skryptów przed i poinstalacyjnych.
.IP "\fB\-\-notriggers\fP"
Nie wywo³uj skryptów, które s± poci±gane przez instalacjê tego pakietu.
.IP "\fB\-\-ignoresize\fP"
Nie sprawdzaj czy na zamontowanych systemach plików jest do¶æ miejsca na
zainstalowanie tego pakietu.
.IP "\fB\-\-excludepath \fI<path>\fP"
Nie instaluj plików, których nazwy rozpoczynaj± siê od \fI<path>\fP.
.IP "\fB\-\-excludedocs\fP"
Nie instaluj ¿adnych plików, które s± zaznaczone jako dokumentacja (co tyczy
siê tak¿e podrêczników man i texinfo).
.IP "\fB\-\-includedocs\fP"
Instaluj pliki dokumentacji. Tak jest domy¶lnie.
.IP "\fB\-\-test\fP"
Nie instaluj pakietu, po prostu sprawd¼ czy istniej± konflikty.
.IP "\fB\-\-ignorearch\fP"
Umo¿liwia to instalacjê, lub od¶wie¿anie nawet w wypadku gdy
architektury binarnego RPM i hosta nie odpowiadaj± sobie.
.IP "\fB\-\-ignoreos\fP"
Umo¿liwia to instalowanie, lub od¶wie¿anie nawet w wypadku gdy systemy
operacyjne binarnego RPM i hosta nie odpowiadaj± sobie.
.IP "\fB\-\-prefix \fI<¶cie¿ka>\fP"
Ustawia to przedrostek instalacji na \fI<¶cie¿kê>\fP dla relokowalnych
pakietów.
.IP "\fB\-\-relocate \fI<stara¶cie¿ka>\fB=\fI<nowa¶cie¿ka>\fP"
W wypadku pakietów relokowalnych, transluje pliki, które by³yby wstawione do
\fI<starej¶cie¿ki>\fP na \fI<now±¶cie¿kê>\fP.
.IP "\fB\-\-badreloc\fP"
Do u¿ytku w po³±czeniu z \-\-relocate. Wymusza relokacjê nawet gdy pakiet
nie jest relokowalny.
.IP "\fB\-\-noorder\fP"
Nie porz±dkuj pakietów dla instalacji. Lista pakietów w normalnych
wypadkach jest porz±dkowana na nowo by spe³niæ zale¿no¶ci.


.SH OPCJE ZAPYTAÑ
Ogóln± postaci± komendy zapytania rpm jest
.PP
	\fBrpm \-q [opcje\-zapytañ]\fP
.PP
Mo¿esz podaæ format, w jakim powinna zostaæ zapisywana informacja pakietowa.
Aby tego dokonaæ, u¿yj opcji \fB[\-\-queryformat|\-qf]\fP, z do³±czonym
³añcuchem formatuj±cym.

Formaty zapytañ s± zmodyfikowanymi wersjami standardowego formatowania
\fBprintf(3)\fP. Format jest z³o¿ony ze statycznych ³añcuchów (które mog±
zawieraæ standardowe znaki specjalne C--dla nowych linii, tabulacji itp.)
oraz formatek typu, podobnych do tych z \fBprintf(3)\fP.
Poniwa¿ \fBrpm\fP ju¿ zna typ do drukowania, specyfikator typu jest
pomijany. W jego miejsce wchodzi nazwa tagu drukowanego nag³ówka, ujêta w
znaki \fB{}\fP. Czê¶æ \fBRPMTAG_\fP nazwy taga mo¿e byæ opuszczona.

Mo¿na za¿±daæ innych formatów wyj¶ciowych przez zakoñczenie taga
\fB:\fItypetag\fR. Obecnie obs³ugiwane s± nastêpuj±ce typy: \fBoctal\fR,
\fBdate\fR, \fBshescape\fR, \fBperms\fR, \fBfflags\fR i \fBdepflags\fR.

Na przyk³ad aby wydrukowaæ tylko nazwy zapytywanych pakietów, mo¿esz u¿yæ
jako ³añcucha formatuj±cego samego \fB%{NAME}\fP. Aby wydrukowaæ nazwy
pakietów i informacje dystrybucji (w dwóch kolumnach), mo¿esz u¿yæ
\fB%\-30{NAME}%{DISTRIBUTION}\fP. (Name bêdzie w 30 znakowym okienku, z
wyrównaniem do lewej--zobacz printf(3)--przyp. t³um.)

Je¶li uruchomiæ go z argumentem \fB\-\-querytags\fP, \fBrpm\fP bêdzie 
drukowa³ listê wszystkich tagów, o których wie.

Istniej± dwa podzbiory opcji dla zapytywania: wybór pakietu i wybór
informacji.

Opcje wyboru pakietu:
.br
.IP "\fB\fI<nazwa_pakietu>\fP"
Zapytaj zainstalowany pakiet o nazwie \fI<nazwa_pakietu>\fP.
.IP "\fB\-a\fP, \fB\-\-all\fP"
Zapytaj wszystkie zainstalowane pakiety.
.IP "\fB\-\-whatrequires \fI<w³a¶ciwo¶æ>\fP"
Zapytaj wszystkie pakiety, wymagaj±ce \fI<w³a¶ciwo¶ci>\fP do prawid³owego
dzia³ania.
.IP "\fB\-\-whatprovides \fI<wirtualna>\fP"
Zapytaj wszystkie pakiety, daj±ce \fI<wirtualn±>\fP w³a¶ciwo¶æ.
.IP "\fB\-f \fI<plik>\fP, \fB\-\-file \fI<plik>\fP"
Zapytaj pakiet, bêd±cy w³a¶cicielem \fI<pliku>\fP.
.IP "\fB\-g \fI<grupa>\fP, \fB\-\-group \fI<grupa>\fP"
Zapytaj pakiety o grupie \fI<grupa>\fP.
.IP "\fB\-p \fI<plik_pakietu>\fP"
Zapytaj (niezainstalowany) pakiet \fI<plik_pakietu>\fP.
Plik ten mo¿e byæ podany w stylu ftp lub http. W takiej sytuacji, przed
zapytaniem zostanie pobrany. Zobacz \fBOPCJE FTP/HTTP\fP.
.IP "\fB\-\-specfile \fI<plikspec>\fP"
Przetwórz i zapytaj \fI<plikspec\fP tak, jakby by³ pakietem. Chocia¿ nie
jest dostêpna ca³a informacja (np. lista plików), to ten typ zapytañ
umo¿liwia u¿ywanie rpm do wyci±gania informacji z plików spec bez potrzeby
pisania specyficznego parsera.
.IP "\fB\-\-querybynumber \fI<num>\fP"
Zapisaj wprost \fI<num>\fP-ty wpis bazy danych; jest to przydatne do
debuggowania.
.IP "\fB\-\-triggeredby \fI<pkg>\fP"
Zapytaj pakiety, które s± poci±gniête przez pakiety \fI<pkg>\fP.

.P
Opcje wyboru informacji:
.br
.IP "\fB\-i\fP"
Wy¶wietl informacjê o pakiecie, ³±cznie z nazw±, wersj± i opisem. O ile
podano \fB\-\-queryformat\fP, to jest on u¿ywany.
.IP "\fB\-R\fP, \fB\-\-requires\fP"
Listuj pakiety, od których zale¿y ten pakiet.
.IP "\fB\-\-provides\fP"
Listuj w³a¶ciwo¶ci, które udostêpnia ten pakiet.
.IP "\fB\-\-changelog\fP"
Wy¶wietl informacje zmian dla tego pakietu.
.IP "\fB\-l\fP, \fB\-\-list\fP"
Listuj pliki z pakietu.
.IP "\fB\-s\fP, \fB\-\-state\fP"
Wy¶wietl \fIstany\fP plików w pakiecie (wymusza \fB\-l\fP).
Stan ka¿dego pliku mo¿e byæ jednym z
\fInormal\fP (normalny), \fInot installed\fP (niezainstalowany), lub 
\fIreplaced\fP (zamieniony).
.IP "\fB\-d\fP, \fB\-\-docfiles\fP"
Listuj tylko pliki dokumentacji (wymusza \fB\-l\fP).
.IP "\fB\-c\fP, \fB\-\-configfiles\fP"
Listuj tylko pliki konfiguracji (wymusza \fB\-l\fP).
.IP "\fB\-\-scripts\fP"
Listuj skrypty pow³oki, specyficzne dla pakietu, które s± u¿ywane jako czê¶æ
procesu instalowania i odinstalowywania (o ile takie skrypty istniej±).
.IP "\fB\-\-triggers\fP, \fB\-\-triggerscripts\fP"
Wy¶wietl skrypty wywo³uj±ce (trigger scripts), zawarte w pakiecie.
.IP "\fB\-\-dump\fP"
Wy¶wietl w nastêpuj±cy sposób informacjê o pliku: ¶cie¿ka rozmiar
czasmodyfukacji sumamd5 prawa w³a¶ciciel grupa jestkonfiguracyjny
jestdokumentacj± rdev dowi±zaniesymboliczne. Musi to byæ u¿yte z
przynajmniej jednym z \fB\-l\fP, \fB\-c\fP, \fB\-d\fP.
.IP "\fB\-\-last\fP"
Porz±dkuje listing pakietów podczas instalowania tak, ¿e ostatnie pakiety s±
na górze.
.IP "\fB\-\-filesbypkg\fP"
Listuje wszystkie pliki z ka¿dego z pakietów.
.IP "\fB\-\-triggerscripts\fP"
Pokazuje wszystkie skrypty wywo³uj±ce (trigger) z wybranych pakietów.

.SH OPCJE WERYFIKACJI
Ogóln± postaci± komendy weryfikacji rpm jest
.PP
	\fBrpm \-V|\-y|\-\-verify [opcje\-weryfikacji]\fP
.PP
Weryfikowanie pakietu porównuje informacje o zainstalowanych plikach w
pakiecie z informacj± o plikach, pobran± z oryginalnego pakietu, zapisanego
w bazie rpm. W¶ród innych rzeczy, porównywane s± rozmiary, sumy MD5, prawa,
typ, w³a¶ciciel i grupa ka¿dego pliku. Wszystkie niezgodno¶ci s± natychmiast
wy¶wietlane. Opcje specyfikacji pakietu s± takie same jak dla zapytywania
pakietów.

Pliki, które nie by³y zainstalowane z pakietu, jak na przyk³ad dokumentacja,
wy³±czona opcj± "\fB\-\-excludedocs\fP", s± cicho ignorowane.

Opcje, których mo¿na u¿yæ w trybie weryfikacji:

.IP "\fB\-\-nofiles\fP"
Ignoruje podczas weryfikacji brakuj±ce pliki.
.IP "\fB\-\-nomd5\fP"
Ignoruje podczas weryfikacji b³êdy sum MD5.
.IP "\fB\-\-nopgp\fP"
Ignoruje podczas weryfikacji b³êdy sprawdzania PGP.
.IP "\fB\-\-nofiles\fP"
Ignoruje podczas weryfikacji brakuj±ce pliki. (dejavu? przyp. t³um. ;)


Format wyj¶cia to ³añcuch 8 znaków, prawdopodobny "\fBc\fP", oznaczaj±cy
plik konfiguracyjny, a nastêpnie nazwa pliku. Ka¿dy z 8 znaków oznacza wynik
porównania jednego atrybutu pliku z warto¶ci± atrybutu, zakodowan± w bazie
RPM. Kropka "\fB.\fP" oznacza, ¿e test przeszed³ pomy¶lnie. Nastêpuj±ce
znaki oznaczaj± b³êdy okre¶lonych testów:

.IP "\fB5\fP"
suma MD5
.IP "\fBS\fP"
rozmiar pliku
.IP "\fBL\fP"
dowi±zanie symboliczne
.IP "\fBT\fP"
czas modyfikacji
.IP "\fBD\fP"
urz±dzenie
.IP "\fBU\fP"
u¿ytkownik
.IP "\fBG\fP"
grupa
.IP "\fBM\fP"
prawa (w³±cza prawa i typ pliku)

.SH SPRAWDZANIE SYGNATURY
Ogóln± postaci± komendy sprawdzania sygnatury jest
.PP
	\fBrpm \-\-checksig \fI<plik_pakietu>+\fP
.PP
Sprawdza to sygnaturê PGP pakietu \fIplik_pakietu\fP aby zapewniæ jego
integralno¶æ i pochodzenie. Informacja konfiguracji PGP jest odczytywana z
plików konfiguracji. Zobacz sekcjê o SYGNATURACH PGP.

.SH OPCJE ODINSTALOWANIA
Ogóln± postaci± komendy odinstalowania rpm jest
.PP
	\fB    rpm \-e \fI<nazwa_pakietu>+\fP
.PP
.IP "\fB\-\-allmatches\fP"
Usuñ wszystkie wersjie pakietu, które odpowiadaj± \fI<nazwie_pakietu\fR.
Normalnie wy¶wietlany jest b³±d gdy nazwa ta odpowiada wielu pakietom.
.IP "\fB\-\-noscripts\fP"
Nie wywo³uj skryptów pre i postinstalacyjnych.
.IP "\fB\-\-notriggers\fP"
Nie wywo³uj skryptów, które s± poci±gane przez usuwanie pakietu.
.IP "\fB\-\-nodeps\fP"
Nie sprawdzaj zale¿no¶ci przed odinstalowaniem.
.IP "\fB\-\-test\fP"
Nie odinstalowuj niczego naprawdê, przejd¼ tylko przez kolejne etapy.
Przydatne w po³±czeniu z opcj± \fB\-vv\fP.

.SH OPCJE BUDOWANIA
Ogóln± postaci± komendy budowania rpm jest
.PP
    \fBrpm \-[b|t]\fIO\fP [opcje\-budowania] \fI<spec_pakietu>+\fP
.PP
Je¶li do zbudowania pakietu u¿ywany jest plik spec, to argumentem powinno
byæ \fB\-b\fR, a je¶li \fBRPM\fR powinien zajrzeæ wewn±trz skompresowanego
pliku tar w poszukiwaniu speca, to powinna byæ u¿yta opcja \fB\-t\fR.
Po pierwszym argumencie, drugi (\fIO\fR) okre¶la etapy budwania i
pakietowania, które nale¿y wykonaæ. Mo¿e to byæ jedno z:

.IP "\fB\-bp\fP"
Wykonuje etap "%prep" z pliku spec. Normalnie wymaga to rozpakowania ¼róde³
i za³±czenia wszelkich ³at.
.IP "\fB\-bl\fP"
Dokonaj sprawdzenia listy. Sekcja "%files" pliku spec jest makro rozwijana i
dokonywane s± sprawdzenia, by upewniæ siê ¿e ka¿dy plik istnieje.
.IP "\fB\-bc\fP"
Wykonaj etap "%build" z pliku spec (po dokonaniu etapu prep).
Ogólnie anga¿uje to ekwiwalenta "make".
.IP "\fB\-bi\fP"
Wykonaj etap "%install" z pliku spec (po dokonaniu etapów prep i build).
Ogólnie anga¿uje to ekwiwalenta
"make install".
.IP "\fB\-bb\fP"
Buduj pakiet binarny (po dokonaniu etapów prep, build i install).
.IP "\fB\-bs\fP"
Buduj pakiet ¼ród³owy (po dokonaniu etapów prep, build i install).
.IP "\fB\-ba\fP"
Buduj pakiety binarny i ¼ród³owy (po dokonaniu etapów prep, build i
install).
.PP
Mog± byæ te¿ u¿yte nastêpuj±ce opcje:
.IP "\fB\-\-short\-circuit\fP"
Przejd¼ wprost do podanego etapu (np. pomiñ wszystkie etapy prowadz±ce do
podanego). Prawid³owe tylko z \fB\-bc\fP i \fB\-bi\fP.
.IP "\fB\-\-timecheck\fP"
Ustaw wiek "sprawdzeniaczasu" (0 wy³±cza). Warto¶æ ta mo¿e byæ te¿
skonfigurowana przez definiowanie makra "_timecheck". Warto¶æ ta wyra¿a w
sekundach maksymalny wiek pakowanego pliku. Dla plików starszych drukowane
bêd± ostrze¿enia.
.IP "\fB\-\-clean\fP"
Usuñ drzewo budowania po stworzeniu pakietów.
.IP "\fB\-\-rmsource\fP"
Usuñ ¼ród³a i plik spec po budowaniu (mo¿e byæ te¿ u¿ywane samodzielnie, np.
"\fBrpm \-\-rmsource foo.spec\fP").
.IP "\fB\-\-test\fP"
Nie wykonuj ¿adnych etapów budowania.
Przydatne do testowania plików spec.
.IP "\fB\-\-sign\fP"
Osad¼ w pakiecie sygnaturê PGP. Sygnatura ta mo¿e byæ u¿ywana do
weryfikowania integralno¶ci i pochodzenia pakietu. Zobacz sekcjê o
SYGNATURACH PGP.
.IP "\fB\-\-buildroot \fI<dir>\fP"
Podczas budowania pakieu przeci±¿ tag BuildRoot na katalog
\fI<dir>\fP.
.IP "\fB\-\-target \fI<platforma>\fP"
Podczas budowania pakietu zinterpretuj \fI<platformê>\fP jako 
\fBarch-vendor-os\fP i ustaw odpowiednio makra \fB_target\fP, 
\fB_target_arch\fP oraz \fB_target_os\fP.
.IP "\fB\-\-buildarch \fI<arch>\fP"
Podczas budowania pakietu, ustaw architekturê na \fI<arch>\fP. Opcja ta
jest przedawniona przez \fB\-\-target\fI z RPM 3.0.
.IP "\fB\-\-buildos \fI<os>\fP"
Podczas budowania pakietu, ustaw architekturê na \fI<os>\fP. Opcja ta jest
przedawniona przez \fB\-\-target\fI z RPM 3.0.


.SH OPCJE PRZEBUDOWANIA I REKOMPILACJI

Istniej± dwa inne sposoby na wywo³anie budowania w rpm:

.I "\fBrpm \-\-recompile \fI<plik_¼ród³owy_pakietu>+\fP"

.I "\fBrpm \-\-rebuild \fI<plik_¼ród³owy_pakietu>+\fP"

Po takim wywo³aniu, \fBrpm\fP instaluje nazwany pakiet ¼ród³owy oraz
dokonuje prep, kompilacji i instalacji. Dodatkowo, \fB\-\-rebuild\fP
buduje nowy pakiet binarny. Po tym jak budowanie jest zakoñczone, katalog
budowania jest usuwany (jak w \fB\-\-clean\fP), a potem ¼ród³a i plik spec 
dla pakietu s± usuwane.

.SH PODPISYWANIE ISTNIEJ¡CEGO RPM

.I "\fBrpm \-\-resign \fI<binarny_plik_pakietu>+\fP"

Opcja ta generuje i wstawia nowe sygnatury do wymienionych pakietów.
Wszelkie istniej±ce sygnatury s± usuwane.

.I "\fBrpm \-\-addsign \fI<binarny_plik_pakietu>+\fP"

Opcja ta generuje i dopisuje nowe sygnatury dla wymienionych pakietów.

.SH SYGNATURY PGP

Aby u¿ywaæ w³a¶ciwo¶ci sygnatur, RPM musi byæ skonfigurowany aby móg³
uruchamiaæ PGP. Musi byæ w stanie znale¼æ pêk kluczy publicznych, w którym
znajduj± siê klucze publiczne RPM. Domy¶lnie, RPM u¿ywa do ich znalezienia
domy¶lnych warto¶ci PGP (honoruj±c PGPPATH). Je¶li twoje klucze nie s±
zlokalizowane tam, gdzie PGP ich oczekuje, mo¿esz skonfigurowaæ makro

.IP "\fB_pgp_path\fP"
na ¶cie¿kê pêków kluczy PGP.
.PP

Je¶li chcesz podpisywaæ pakiety, które sam tworzysz, mo¿esz te¿ potrzebowaæ
utworzyæ swój w³asny klucz publiczny i poufny (zobacz podrêcznik PGP, pgp(1))
Bêdziesz te¿ potrzebowa³ skonfigurowaæ makra

.IP "\fB_signature\fP"
Typ sygnatury. Obecnie obs³ugiwany jest tylko pgp.
.IP "\fB_pgp_name\fP"
Nazwa "u¿ytkownika", którego klucz bêdzie u¿ywany do podpisu.
.PP

Podczas budowania pakietów tzeba wtedy dodaæ w linii komend \-\-sign.
Bêdziesz zapytany o swoj± frazê koduj±c±, a twój pakiet zostanie zbudowany i
podpisany.

Na przyk³ad, aby u¿yæ PGP do podpisania pakietów jako u¿ytkownik
\fp"John Doe <jdoe@foo.com>"\fP z pêku kluczy, zlokalizowanego w
\fB/etc/rpm/.pgp\fP, za³±czy³by¶

.IP "\fB%_signature\fP"
\fBpgp\fP
.IP "\fB%_pgp_name\fP"
\fB/etc/rpm/.pgp\fP
.IP "\fB%_pgp_name\fP"
\fBJohn Doe <jdoe@foo.com>"
.PP

w pliku konfiguracji makr. Do ogólnosystemowej konfiguracji u¿yj
\fB/etc/rpm/macros\fP, a dla lokalnej \fB~/.rpmmacros\fP.

.SH OPCJE PRZEBUDOWYWANIA BAZY DANYCH

Ogólna postaæ komendy przebudowywania bazy danych rpm to
.PP
	\fBrpm \-\-rebuilddb\fP
.PP

Aby przebudowaæ now± bazê danych, wykonaj:
.PP
	\fBrpm \-\-initdb\fP
.PP

Jedynymi opcjami dla tych trybów s± \fB-\-dbpath\fP i
\fB-\-root\fP.

.SH SHOWRC 

Uruchamianie

.PP
	\fBrpm \-\-showrc\fP

.PP
pokazuje warto¶ci, których RPM bêdzie u¿ywa³ dla wszystkich opcji, które
mog± byæ ustawione w plikach \fIrpmrc\fP.

.SH OPCJE FTP/HTTP

RPM zawiera prostych klientów FTP i HTTP, które upraszczaj± instalowanie i
zapytywanie pakietów, które s± dostêpne w sieci. Pliki pakietów mo¿na
podawaæ w url'u w stylu ftp lub http:

.PP
	\fBftp://<u¿ytkownik>:<has³o>@host:<port>/¶cie¿ka/pakietu.rpm\fP
.PP
Je¶li czê¶æ \fB:has³o\fP jest pominiêta, u¿ytkownik zostanie o nie zapytany
(jednokrotnie na parê u¿ytkownik/host). Je¶li pominiêto nazwê u¿ytkownika i
has³o, u¿ywany jest anonimowy ftp. We wszystkich przypadkach u¿ywane s±
pasywne (PASV) transfery ftp.

RPM zezwala na u¿ywanie z URL-ami FTP nastêpuj±cych opcji:

.IP "\fB\--ftpproxy \fI<host>\fP"
Podany host bêdzie u¿ywany jako proxy dla wszystkich transferów ftp, co
umo¿liwia u¿ytkownikom ftp przez maszyny ¶cian ognia, które u¿ywaj± systemów
proxy.
Opcja ta mo¿e byæ te¿ podana przez skonfigurowanie makra \fB_ftpproxy\fP.

.IP "\fB\--ftpport \fI<port>\fP"
Numer portu TCP, którego u¿yæ do po³±czenia ftp na serwerze proxy, zamiast
portu domy¶lnego. Opcja ta mo¿e byæ te¿ podana przez skonfigurowanie makra
\fB_ftpport\fP.
.PP

RPM zezwala na u¿ywanie z URL-ami HTTP nastêpuj±cych opcji:

.IP "\fB\--httpproxy \fI<host>\fP"
Podany host bêdzie u¿ywany jako proxy dla wszystkich transferów http.
Opcja ta mo¿e byæ te¿ podana przez skonfigurowanie makra \fB_httpproxy\fP.

.IP "\fB\--httpport \fI<port>\fP"
Numer portu TCP, którego u¿yæ do po³±czenia http na serwerze proxy zamiast
portu domy¶lnego. Opcja ta mo¿e byæ te¿ podana przez skonfigurowanie makra
\fB_httpport\fP.
.PP

.SH PLIKI
.nf
/usr/lib/rpm/rpmrc
/etc/rpmrc
~/.rpmrc
/var/lib/rpm/packages
/var/lib/rpm/pathidx
/var/lib/rpm/nameidx
/tmp/rpm*
.fi
.El
.SH ZOBACZ TAK¯E
.IR glint (8) ,
.IR rpm2cpio (8) ,
.B http://www.rpm.org/
.nf
.SH AUTORZY
.nf
Marc Ewing <marc@redhat.com>
Jeff Johnson <jbj@redhat.com>
Erik Troan <ewt@redhat.com>
.fi
