.\" {PTM/WK/1999-11-21}
.\" Jakub Bogusz <qboosh@pld-linux.org>, 2003
.\" rpm2cpio - Converts RPM Package to cpio archive
.\" rpm 4.3-20030610
.TH rpm2cpio 8 "11 stycznia 2001" "Red Hat, Inc."
.SH NAZWA
rpm2cpio \- konwersja pakietu RPM na archiwum cpio
.SH SKŁADNIA
\fBrpm2cpio\fP [ nazwa_pliku ]
.SH OPIS
\fBrpm2cpio\fP konwertuje podany, jako jedyny argument, plik .rpm
do postaci archiwum cpio na standardowym wyjściu. Jeśli podano argument '-',
to strumień rpm czytany jest ze standardowego wejścia.

.br
.I "\fBrpm2cpio rpm-1.1-1.i386.rpm\fP"
.br
.I "\fBrpm2cpio < glint-1.0-1.i386.rpm\fP"
.br
.I "\fBrpm2cpio glint-1.0-1.i386.rpm | cpio -dium\fP"

.SH ZOBACZ TAKŻE
.IR rpm (8)
.SH AUTOR
.nf
Erik Troan <ewt@redhat.com>
.fi
