.\" Jakub Bogusz <qboosh@pld-linux.org>, 2003
.\" rpm 4.3-20030610
.TH "RPMCACHE" "8" "5 lipca 2002" "Red Hat, Inc." "Red Hat Linux"
.SH NAZWA
rpmcache \- Zapamiętywanie nagłówków pakietów RPM
.SH SKŁADNIA
.PP

\fBrpmcache\fR [ \fB\fINAZWA_PAKIETU\fB\fR\fI ...\fR ]

.SH "OPIS"
.PP
\fBrpmcache\fR chodzi po drzewie plików (być może także zdalnych
przy użyciu \fBFTP\fR), filtrując ścieżki przy użyciu wyrażeń
\fBglob\fR(7), czytając nagłówki pakietów rpm. Ostatnie (porównując
pola epoch/version/release pakietów w przypadku identycznych nazw
i używając czasu budowania w przypadkach nierozstrzygniętych)
nagłówki pakietów, jeśli są unikalne, są zapamiętywane w bazie danych
rpm-a. Zapamiętane w bazie nagłówki mogą być używane do udostępniania
sugerowanych ścieżek do pakietów rozwiązujących nieznane zależności.
.PP
Nie ma opcji specyficznych dla \fBrpmcache\fR, tylko wspólne opcje
\fBrpm\fR-a. Aktualnie zaimplementowane opcje można zobaczyć w komunikacie
o składni komendy \fBrpmcache\fR.
.PP
Ścieżka drzewa plików do przeszukiwania jest konfigurowana przy użyciu
makr rpm-a. Ostateczna ścieżka jest połączeniem 5 oddzielnych elementów.
Oto nazwy makr używanych do skonfigurowania \fBrpmcache\fR w tej samej
kolejności, w jakiej są łączone w celu stworzenia ścieżki drzewa plików
do przeszukania:
.PP
.TP
\fB%_bhpath\fR
Poziom "path" (ścieżka) zawiera początkową część ścieżki drzewa plików
(lub URL). Proszę tu nie używać wyrażeń \fBglob\fR(7).
.TP
\fB%_bhcoll\fR
Poziom "collection" (kolekcja) zawiera łańcuch (lub wyrażenie
\fBglob\fR(7)) określający podkatalogi \fB%_bhpath\fR.
.TP
\fB%_bhN\fR
Poziom "name" (nazwa) zawiera łańcuch (lub wyrażenie \fBglob\fR(7))
określający podkatalogi \fB%_bhcoll\fR.
Argumenty \fINAZWA_PAKIETU\fR są używane do stworzenia wyrażenia
\fBglob\fR(7), które będzie pasowało do określonych nazw pakietu
w systemie budowania Red hata, i są raczej bezużytecznie poza Red
Hatem.
.TP
\fB%_bhVR\fR
Poziom "version-release" (wersja-wydanie) zawiera łańcuch (lub wyrażenie
\fBglob\fR(7)) określający podkatalogi \fB%_bhN\fR.
.TP
\fB%_bhA\fR
Poziom "arch" (architektura) zawiera łańcuch (lub wyrażenie
\fBglob\fR(7)) określający podkatalogi \fB%_bhVR\fR.
.PP
Położenie bazy danych pamiętającej nagłówki jest konfigurowalne poprzez
makro rpm-a:
.TP
\fB%_cache_dbpath\fR
Położenie bazy danych pamiętającej nagłówki. Domyślna wartość to
\fI/var/spool/up2date/cache\fR.
.PP
Baza danych nagłówków ma identyczny format do bazy danych rpm-a
i może być używana z linii poleceń \fBrpm\fR-a. Na przykład aby
użyć bazy danych nagłówków do udostępnienia sugestii dla pakietów
dostarczających zależności potrzebne do zainstalowania pakietu,
następujące makro musi być skonfigurowane w
\fI/etc/rpm/macros\fR lub
\fI~/.rpmmacros\fR:
.TP
\fB%_solve_dbpath\fR
Położenie bazy danych używanej do udostępniania sugestii do
rozwiązywania zależności.
.PP
.SS "Przykładowa (minimalna) konfiguracja dla drzewa beehive Red Hata:"
.PP
.nf
%_cache_dbpath  /var/spool/up2date/cache
%_solve_dbpath  %{_cache_dbpath}
%_bhpath        file://localhost/mnt/redhat/beehive/comps/dist
%_bhcoll        7.3
%_bhN           @(basesystem|bash|filesystem|glibc-common|glibc|ldconfig|libtermcap|mktemp|setup|termcap)
%_bhVR          *
%_bhA           @(i[3456]86|noarch)
.fi
.SS "Przykładowa (minimalna) konfiguracja dla drzewa FTP Red Hata:"
.PP
.nf
%_cache_dbpath  /var/spool/up2date/cache
%_solve_dbpath  %{_cache_dbpath}
%_bhpath        ftp://localhost/mnt/dist
%_bhcoll        @(7.3|7.2|7.1|7.0|6.2|6.1|6.0|5.2|5.1|5.0)
%_bhN           @(%{_arch})
%_bhVR          *
%_bhA           @(i[3456]86|noarch)
.fi
.SH "BŁĘDY"
.PP
Uhm. Proszę wypełniać raporty o błędach i życzeniach dla pakietu rpm-devel
przy użyciu bugzilli (w języku angielskim):
http://bugzilla.redhat.com/ <URL:http://bugzilla.redhat.com/>
.SH "ZOBACZ TAKŻE"

\fBrpm\fR(8),
\fBglob\fR(7),

\fB http://www.rpm.org/ <URL:http://www.rpm.org/>
\fR
.SH "AUTORZY"

Jeff Johnson <jbj@redhat.com>
