.\" Jakub Bogusz <qboosh@pld-linux.org>, 2003
.\" rpm 4.3-20030610
.TH "RPMDEPS" "8" "24 października 2002" "Red Hat, Inc."
.SH NAZWA
rpmdeps \- Generowanie zależności pakietów RPM
.SH SKŁADNIA
.PP

\fBrpmdeps\fR \fB{-P|--provides}\fR \fB{-R|--requires}\fR \fB\fIPLIK\fB\fR\fI ...\fR

.SH "OPIS"
.PP
\fBrpmdeps\fR generuje zależności pakietu dla zbioru argumentów
\fBPLIKOWYCH\fR. Każdy argument \fBPLIKOWY\fR jest przeszukiwany pod
kątem Elf32/Elf64, interpretera skryptów lub zależności dla skryptu,
a zależności są wypisywane na standardowe wyjście.
.SH "ZOBACZ TAKŻE"

\fBrpm\fR(8),

\fBrpmbuild\fR(8),
.SH "AUTORZY"

Jeff Johnson <jbj@redhat.com>
