#!/usr/bin/env bash

DESTDIR="${DESTDIR:-/}"
pkglibdir="${pkglibdir:-/usr/lib/rpm}"
platformdir="${pkglibdir}/platform"

RPMRC="${1:-rpmrc}"
MACROS="${2:-macros}"
PLATFORM="${3:-platform}"

RPM="./rpm --rcfile=$RPMRC --macros=$MACROS"

canonarch_sed='s_i.86_i386_;s_pentium[34]_i386_;s_athlon_i386_;s_sparc[^-]*_sparc_;s_alpha[^-]*_alpha_;s_arm[^-]*_arm_;s_\(powerpc\|ppc\)[^-]*_ppc_;s,\(ia32e\|amd64\),x86_64,;s_sh4a_sh4_'
arch="`$RPM --eval '%{_arch}'|sed -e "$canonarch_sed"`"
VENDOR="`$RPM --eval '%{_vendor}'`"
OS="`$RPM --eval '%{_os}'`"
RPMRC_GNU="`$RPM --eval '%{_gnu}'`"

for ARCH in `grep ^arch_canon $RPMRC | cut -d: -f2`; do
  RPMRC_OPTFLAGS="`sed -n 's/^optflags: '$ARCH' //p' $RPMRC`"
  RPMRC_OPTFLAGS="`echo $RPMRC_OPTFLAGS | sed -e 's, ,\ ,g'`"
  case $RPMRC_OPTFLAGS in
  *-g*) ;;
  *) RPMRC_OPTFLAGS="$RPMRC_OPTFLAGS -g" ;;
  esac

  ARCH_INSTALL_POST='%{nil}'
  case "${ARCH}-${OS}" in
    sparc64*-linux) LIB=lib64 ;;
    s390x-linux) LIB=lib64 ;;
    ppc64-linux|powerpc64-linux) LIB=lib64 ;;
    x86_64-linux|amd64-linux|ia32e-linux) LIB=lib64 ;;
    *) LIB=lib;;
  esac

  # XXX FIXME: incomplete and quite likely wrong too in places,
  # consult various arch folks for correct names etc.
  ISANAME=
  ISABITS=
  case "${ARCH}" in
    sparc64*) 
	ISANAME=sparc
	ISABITS=64
	;;
    sparc*) 
	ISANAME=sparc
	ISABITS=32
	;;
    s390)
	ISANAME=s390
	ISABITS=32
	;;
    s390x)
	ISANAME=s390
	ISABITS=64
	;;
    ppc64*)
	ISANAME=ppc
	ISABITS=64
	;;
    ppc*)
	ISANAME=ppc
	ISABITS=32
	;;
    i?86|pentium?|athlon|geode)
	ISANAME=x86
	ISABITS=32
	;;
    x86_64|amd64|ia32e)
	ISANAME=x86
	ISABITS=64
	;;
    ia64)
	ISANAME=ia
	ISABITS=64
	;;
    sh*)
	ISANAME=sh
	ISABITS=32
	;;
    arm*)
	ISANAME=`echo ${ARCH} | sed "s/^\([^-]*\)-.*/\1/"`
	ISABITS=32
	;;
    alpha*)
	ISANAME=alpha
	ISABITS=64
	;;
  esac

  # skip architectures for which we dont have full config parameters
  [ -z "$ISANAME" ] && continue

  CANONARCH="`echo $ARCH|sed -e "$canonarch_sed"`"

  PPD="${DESTDIR}/${platformdir}/${ARCH}-${OS}"
  [ -d $PPD ] || mkdir -p $PPD

  cat $PLATFORM \
  | sed -e "s,@RPMRC_OPTFLAGS@,$RPMRC_OPTFLAGS," \
	-e "s,$arch,$CANONARCH," \
	-e "s,@RPMRC_GNU@,$RPMRC_GNU," \
	-e "s,@LIB@,$LIB," \
	-e "s,@ARCH_INSTALL_POST@,$ARCH_INSTALL_POST," \
	-e '/\${\w*:-/!s,\${,%{_,' \
	-e "s,@ISANAME@,$ISANAME," \
	-e "s,@ISABITS@,$ISABITS," \
	-e "s,^@${VENDOR}@,," \
  | grep -v '^@' \
  > ${PPD}/macros

done

{ cd ${DESTDIR}/${platformdir}
  [ -L noarch-${OS} ] && rm -f noarch-${OS} 2>/dev/null
  mkdir -p noarch-${OS}
  sed -e "/^%_arch/s,${arch},noarch," ${arch}-${OS}/macros | grep -v '^%optflags' | grep -v "^%__isa" > noarch-${OS}/macros
}
