.\" rpm - Red Hat Package Manager
.\"
.\" translated into slovak by Peter Ivanyi <ivanyi@internet.sk>
.\" for rpm version 3.0.5-9.6x
.\"
.TH rpm 8 "22 December 1998" "Red Hat Software"

.SH MENO
rpm \- Red Hat správca balíkov

.SH POUŽITIE
\fBrpm\fP [voľby] 

.SH POPIS
\fBrpm\fP je veľmi výkonný \fIsprávca balíkov\fP, ktorý môže byť
použitý na zostavenie, inštaláciu, výpis informácií, kontrolu,
aktualizáciu a odinštalovanie jednotlivých softverových balíkov.
\fIBalík\fP obsahuje archív súborov a informácií o balíku vrátane
mena, verzie a popisu.

Musí byť použitý v niektorom z nasledujúcich režimov:
\fIinicializácia databázy\fP, \fIprebudovanie databázy\fP,
\fIzostavenie balíka\fP, \fIrekompilácia balíka\fP,
\fIzostavenie balíka z tar archívu\fP, \fIzistenie informácií\fP,
\fIvýpis informačných tagov\fP, \fIinštalácia\fP, \fIobčerstvenie\fP,
\fIodinštalovanie\fP, \fIkontrola a overenie\fP, \fIoverenie podpisu\fP,
\fIopätovný podpis\fP, \fIpridanie podpisu\fP,
\fInastavenie vlastníkov a skupín\fP a \fIvýpis konfigurácie\fP.

Spravovanie databázy:
.br
.I "\fB    rpm \-i [\-\-initdb]\fP"
.br
.I "\fB    rpm \-i [\-\-rebuilddb]\fP"

Zostavenie:
.br
.I "\fB    rpm [\-b|t] [balík_spec]+\fP"
.br
.I "\fB    rpm [\-\-rebuild] [zdrojové_rpm]+\fP"
.br
.I "\fB    rpm [\-\-tarbuild] [tarovaný_zdroj]+\fP"
.br

Zistenie informácií:
.br
.I "\fB    rpm [\-\-query] [zisťovacie\-voľby]\fP"
.br
.I "\fB    rpm [\-\-querytags]\fP"
.br

Spravovanie inštalovaných balíkov:
.br
.I "\fB    rpm [\-\-install] [inštalačné\-voľby] [súbor_balíka]+\fP"
.br
.I "\fB    rpm [\-\-freshen|\-F] [inštalačné\-voľby] [súbor_balíka]+\fP"
.br
.I "\fB    rpm [\-\-uninstall|\-e] [odinštalačné\-voľby] [balík]+\fP"
.br
.I "\fB    rpm [\-\-verify|\-V] [overovacie\-voľby] [balík]+\fP"
.br

Podpisy (signatúry):
.br
.I "\fB    rpm [\-\-verify|\-V] [overovacie\-voľby] [balík]+\fP"
.br
.I "\fB    rpm [\-\-resign] [súbor_balíka]+\fP"
.br
.I "\fB    rpm [\-\-addsign] [súbor_balíka]+\fP"
.br

Rozličné:
.br
.I "\fB    rpm [\-\-showrc]\fP"
.br
.I "\fB    rpm [\-\-setperms] [balík]+\fP"
.br
.I "\fB    rpm [\-\-setgids] [balík]+\fP"
.br


.SH VŠEOBECNÉ VOĽBY
Tieto voľby môžu byť použité vo všetkých režimoch.
.IP "\fB\-vv\fP"
Vypíše množstvo ošklivých ladiacich informácií.
.IP "\fB\-\-quiet\fP"
Vypíše čo najmenej informácií \- normálne sa zobrazia iba chybové hlášky.
.IP "\fB\-\-help\fP"
Vypíše o niečo dlhšiu informáciu o použití ako je bežný výpis.
.IP "\fB\-\-version\fP"
Vypíše jednoriadkovú informáciu pozostávajúcu z čísla používanej verzie
\fBrpm\fP.
.IP "\fB\-\-rcfile \fI<zoznam_súborov>\fP"
Každý zo súborov v \fI<zoznam_súborov>\fP oddelených dvojbodkami je
postupne čítaný cez \fBrpm\fP za účelom získania konfiguračných informácií.
Implicitný \fI<zoznam súborov>\fP je
\fB/usr/lib/rpm/rpmrc:/etc/rpmrc:~/.rpmrc\fP.
Iba prvý súbor zo zoznamu súborov musí existovať, a vlnovky (~) sú
expandované na hodnotu \fB$HOME\fP.
.IP "\fB\-\-root \fI<adresár>\fP"
Použije adresár \fI<adresár>\fP ako koreňový adresár systému pre všetky operácie.
Uvedomte si, že toto znamená, že databáza sa sa bude čítať alebo modifikovať
pod adresárom \fI<adresár>\fP a všetky predinštalačné a poinštalačné skripty
budú bežať po prevedení chroot() na adresár \fI<adresár>\fP.
.IP "\fB\-\-dbpath \fI<cesta>\fP"
Použije databázu RPM v ceste \fI<cesta>\fP.
.IP "\fB\-\-justdb\fP"
Aktualizuje iba databázu a nie súborový systém.
.IP "\fB\-\-ftpproxy \fI<počítač>\fP, \fB\-\-httpproxy \fI<počítač>\fP"
Použije \fI<počítač>\fP ako počítač s FTP alebo HTTP proxy serverom.
Bližšie podrobnosti sú uvedené v sekcii \fBVOĽBY FTP/HTTP\fP.
.IP "\fB\-\-ftpport \fI<port>\fP, \fB\-\-httpport \fI<port>\fP"
Použije \fI<port>\fP ako FTP alebo HTTP port na počítači s proxy serverom.
Bližšie podrobnosti sú uvedené v sekcii \fBVOĽBY FTP/HTTP\fP.
.IP "\fB\-\-pipe \fI<príkaz>\fP"
Presmeruje výstup \fBrpm\fP na príkaz \fI<príkaz>\fP.


.SH VOĽBY PRI INŠTALÁCII A AKTUALIZÁCII (UPGRADE)
Všeobecná forma inštalačného príkazu je
.PP
	\fBrpm \-i [inštalačné\-voľby] \fI<súbor_balíka>+\fP
.PP
Táto voľba nainštaluje nový balíček.
Všeobecná forma aktualizačného príkazu je
.PP
	\fBrpm \-U [inštalačné\-voľby] \fI<súbor_balíka>+\fP
.PP
Táto voľba aktualizuje existujúci nainštalovaný balíček alebo nainštaluje
nový balíček. Podobá sa inštalačnému príkazu, rozdiel je iba v tom, že
všetky ďaľšie verzie balíka sa odstránia zo systému.
.PP
	\fBrpm [\-F|--freshen] [inštalačné\-voľby] \fI<súbor_balíka>+\fP
.PP
Táto voľba aktualizuje balíky, ale iba za predpokladu, že predchádzajúce
verzie sú nainštalované.

\fI<súbor_balíka>\fP môže byť špecifikovaný ako ftp alebo http URL,
v tomto prípade sa najprv balíček stiahne a nainštaluje až potom.
Bližšie podrobnosti o vstavanej podpore ftp a http sú uvedené v sekcii
\fBVOĽBY FTP/HTTP\fP.
.PP
.IP "\fB\-\-force\fP"
Rovnaký efekt ako súčasné použitie \fB\-\-replacepkgs\fP, \fB\-\-replacefiles\fP a 
\fB\-\-oldpackage\fP.
.IP "\fB\-h\fP, \fB\-\-hash\fP"
Vypíše 50 znakov #, keď je celý archív balíka rozbalený. Pre lepší
vzhľad je vhodné používať s voľbou \fB\-v\fP.
.IP "\fB\-\-oldpackage\fP"
Povolí aktualizáciu prepísaním novšieho balíka starším.
.IP "\fB\-\-percent\fP"
Vypíše stav rozbalovania súborov z balíkového archívu v percentách.
Toto je praktické pri behu RPM z iných nástrojov.
.IP "\fB\-\-replacefiles\fP"
Nainštaluje balík aj v prípade, že nahradí súbory z iných, už
nainštalovaných balíkov.
.IP "\fB\-\-replacepkgs\fP"
Nainštaluje balíky aj v prípade, že niektoré z nich už sú nainštalované
v systéme.
.IP "\fB\-\-allfiles\fP"
Nainštaluje alebo aktualizuje všetky missingok súbory (súbory, ktoré nemusia
nutne existovať) z balíka bez ohľadu na to, či existujú.
.IP "\fB\-\-nodeps\fP"
Nevykoná kontrolu závislostí pred inštalovaním alebo aktualizovaním
balíka.
.IP "\fB\-\-noscripts\fP"
Nevykoná predinštalačné a poinštalačné skripty.
.IP "\fB\-\-notriggers\fP"
Nevykoná skripty, ktorých spúšťou je inštalácia balíka.
.IP "\fB\-\-ignoresize\fP"
Nevykoná kontrolu pripojeného súborového systému na dostatok voľného miesta
pred inštaláciou balíka.
.IP "\fB\-\-excludepath \fI<cesta>\fP"
Nenainštaluje súbory, ktorých mená začínajú na \fI<cesta>\fP.
.IP "\fB\-\-excludedocs\fP"
Nenainštaluje žiadne súbory, ktoré sú označené ako dokumentácia (ktoré
zahŕňajú najmä manuálové stránky a texinfo dokumenty).
.IP "\fB\-\-includedocs\fP"
Nainštaluje súbory, ktoré sú označené ako dokumentácia. Toto je implicitné
nastavenie.
.IP "\fB\-\-test\fP"
Nenainštaluje balík, iba jednoducho otestuje, čo by sa vykonalo pri
inštalácii a vypíše potenciálne konflikty.
.IP "\fB\-\-ignorearch\fP"
Toto umožní inštaláciu alebo aktualizáciu aj v prípade, že sa nezhoduje
architektúra popísaná v binárnom RPM a počítača, na ktorý sa má balík
inštalovať.
.IP "\fB\-\-ignoreos\fP"
Toto umožní inštaláciu alebo aktualizáciu aj v prípade, že sa nezhoduje
operačný systém popísaný v binárnom RPM a počítači, na ktorý sa má balík
inštalovať.
.IP "\fB\-\-prefix \fI<cesta>\fP"
Toto nastaví inštalačný prefix na \fI<cesta>\fP pre relokovateľné
(premiestniteľné) balíky.
.IP "\fB\-\-relocate \fI<stará_cesta>\fB=\fI<nová_cesta>\fP"
Pre relokovateľné balíky, preloží cestu súborov, ktoré sa mali umiestniť
na miesto \fI<stará_cesta>\fP do \fI<nová_cesta>\fP.
.IP "\fB\-\-badreloc\fP"
Vnúti relokáciu aj v prípade, že balík nie je relokovateľný. Používa sa
spolu s voľbou \-\-relocate.
.IP "\fB\-\-noorder\fP"
Nezmení poradie balíkov na inštaláciu. V opačnomom prípade by mohlo byť
zmenené poradie v zozname balíkov, aby sa zachovali závislosti.


.SH VOĽBY PRI ZISTENÍ INFORMÁCIÍ (QUERY)
Všeobecná forma príkazu zistenia informácií je
.PP
	\fBrpm \-q [zisťovacie\-voľby]\fP
.PP
Je možné špecifikovať, v akom formáte majú byť vypísané výstupné údaje.
Na takýto účel slúži voľba \fB[\-\-queryformat|\-\-qf]\fP, nasledovaná
formátovacím reťazcom.

Informačné výstupy sú modifikovanou verziou štandardného \fBprintf(3)\fP
formátovania. Formát je vytvorený zo statických reťazcov (ktoré môžu zahŕňať
štandardné C znakové escape sekvencie pre nový riadok, tabelátor a ďaľšie
špeciálne znaky a \fBprintf(3)\fP typové formátovače). Keďže \fBrpm\fP už
vie, aky typ má vytlačiť, špecifikátor typu musí byť vynechaný a nahradený
menom tagu hlavičky, ktorá má byť vytlačená, uzavretý znakmi {}. RPMTAG_
časť mena tagu môže byť vynechaná.

Alternatívny výstup formátovania môže byť požadovaný, ak je nasledovaný
tagom s \fB:\fItypetag\fR. Momentálne sú podporované nasledujúce typy:
\fBoctal\fR, \fBdate\fR, \fBshescape\fR, \fBperms\fR, \fBfflags\fR, a
\fBdepflags\fR.

Napríklad na vytlačenie informácie o mene balíka je možné použiť
formátovací reťazec \fB%{NAME}\fP. Na vytlačenie informácie o mene
a distribúcii v dvoch stĺpcoch je možné použiť
\fB%\-30{NAME}%{DISTRIBUTION}\fP.

\fBrpm\fP zobrazí zoznam všetkých tagov, ktoré pozná, keď je spustené
s argumentom \fB\-\-querytags\fP.

Existujú dve podmnožiny volieb pre zistenie informácií: výber balíka a
výber informácií.

Voľby výberu balíka:
.br
.IP "\fB\fI<meno_balíka>\fP"
Zisťuje u inštalovaných balíkov s menom \fI<meno_balíka>\fP.
.IP "\fB\-a\fP, \fB\-\-all\fP"
Zisťuje u všetkých nainštalovaných balíkov.
.IP "\fB\-\-whatrequires \fI<schopnosť>\fP"
Zisťuje u všetkých inštalovaných balíkov, ktoré vyžadujú \fI<schopnosť>\fP
pre správnu funkčnosť.
.IP "\fB\-\-whatprovides \fI<virtuálna_schopnosť>\fP"
Zisťuje u všetkých inštalovaných balíkov, ktoré poskytujú vlastnosť
\fI<virtuálna_schopnosť>\fP.
.IP "\fB\-f \fI<file>\fP, \fB\-\-file \fI<file>\fP"
Zisťuje u balíka, ktorý vlastní súbor \fI<file>\fP.
.IP "\fB\-g \fI<group>\fP, \fB\-\-group \fI<group>\fP"
Zisťuje u balíkov, ktoré majú skupinu \fI<group>\fP.
.IP "\fB\-p \fI<súbor_balíka>\fP"
Zisťuje u (nenainštalovaného) balíka \fI<súbor_balíka>\fP.
\fI<súbor_balíka>\fP môže byť špecifikovaný v ftp alebo http štýle URL,
v takomto prípade bude stiahnutá hlavička balíka, a z nej čítané požadované
informácie. Bližšie informácie o vstavanej podpore ftp a http klienta sú
v sekcii \fBFTP/HTTP VOĽBY\fP.
.IP "\fB\-\-specfile \fI<spec_súbor>\fP"
Rozanalyzuje \fI<spec_súbor>\fP a zisťuje informácie z tohto súboru, ako keby
to bol balík rpm. Aj napriek neprítomnosti všetkých informácií (napr. zoznam
súborov), tento druh zisťovania umožňuje rpm získať informácie zo spec súboru
bez nutnosti napísať špeciálny analyzátor spec súborov.
.IP "\fB\-\-querybynumber \fI<číslo>\fP"
Zisťuje u záznamu číslo \fI<číslo>\fP databázy priamo, toto je užitočné pre
ladiace účely.
.IP "\fB\-\-triggeredby \fI<balík>\fP"
Vypíše balíky, ktorých spúštou je existencia balíka \fI<balík>\fP.

.P
Voľba výberu informácií:
.br
.IP "\fB\-i\fP"
Vypíše informácie o balíku, vrátane mena, verzie a popisu. Táto voľba
využíva \fB\-\-queryformat\fP, ak je špecifikovaný.
.IP "\fB\-R\fP, \fB\-\-requires\fP"
Vypíše zoznam balíkov, na ktorých daný balík závisí.
.IP "\fB\-\-provides\fP"
Vypíše zoznam vlastností/schopností, ktoré poskytuje tento balík.
.IP "\fB\-\-changelog\fP"
Vypíše históriu zmien pre balík.
.IP "\fB\-l\fP, \fB\-\-list\fP"
Vypíše zoznam súborov v balíku.
.IP "\fB\-s\fP, \fB\-\-state\fP"
Vypíše \fIstavy\fP jednotlivých súborov v balíku (aplikuje voľbu
\fB\-l\fP). Stav jednotlivých súborov môže byť \fInormal\fP (normálny),
\fInot installed\fP (nenainštalovaný) alebo \fIreplaced\fP (nahradený).
.IP "\fB\-d\fP, \fB\-\-docfiles\fP"
Vypíše zoznam súborov označených ako dokumentácia (aplikuje \fB\-l\fP).
.IP "\fB\-c\fP, \fB\-\-configfiles\fP"
Vypíše iba zoznam konfiguračných súborov (aplikuje \fB\-l\fP).
.IP "\fB\-\-scripts\fP"
Vypíše balíkovo špecifický shellový skript, ktorý je použitý
v inštalačnom alebo odinštalačnom procese, ak nejaký vôbec existuje.
.IP "\fB\-\-triggers\fP, \fB\-\-triggerscripts\fP"
Vypíše skripty, ktoré sú spúšťané spúšťou, ak nejaká existuje a je
obsiahnutá v balíku.
.IP "\fB\-\-dump\fP"
Vypíše zoznam podrobných vlastností súborov pozostoávajúci z:
cesta veľkosť mtime md5sum mód vlastník skupina je_konfiguračný_súbor
je_dokumentačný_súbor rdev symlink. Táto voľba musí byť použitá
minimálne s jednou z nasledujúcich volieb \fB\-l\fP, \fB\-c\fP, \fB\-d\fP.
.IP "\fB\-\-last\fP"
Usporiada zoznam balíkov podľa času inštalácie takým spôsobom, že posledný
inštalovaný balík bude na vrchu.
.IP "\fB\-\-filesbypkg\fP"
Vypíše zoznam všetkých súborov v každom balíku.
.IP "\fB\-\-triggerscripts\fP"
Vypíše všetky skripty, ktoré sú spúšťané spúšťou vo vybranom balíku.


.SH VOĽBY PRI KONTROLE A OVEROVANÍ
Všeobecná forma príkazu kontroly je
.PP
	\fBrpm \-V|\-y|\-\-verify [overovacie\-voľby]\fP
.PP
Kontrola balíka prebieha z porovnania informácií z inštalovaných súborov
z balíkov v systéme s informáciami o súboroch, ktoré obsahoval pôvodný balík
(tieto su uložené v rpm databáze). Okrem iných údajov, kontrola porovnáva
veľkosť, MD5 kontrolný súčet, oprávnenia, typ, vlastníka a skupinu každého
súboru. Všetky odchýľky sú zobrazené. Specifikačné voľby balíka sú rovnaké
ako režime výpisu informácii balíkov.

Súbory, ktoré neboli inštalované z balíka, týkajúce sa napr. dokumentačných
súborov pri použití voľby "\fB\-\-excludedocs\fP" pri inštalácii, sú v
tichosti ignorované.

Voľby, ktoré môžu byť použité v kontrolnom režime:

.IP "\fB\-\-nofiles\fP"
Ignoruje chýbajúce súbory v systéme počas kontroly.
.IP "\fB\-\-nomd5\fP"
Ignoruje chyby kontrolných súčtov MD5 počas kontroly.
.IP "\fB\-\-nopgp\fP"
Ignoruje chyby PGP podpisov počas kontroly.

Výstup má formát 9 znakového reťazca, s prípadným rozšírením výskytu
"\fBc\fP", ktoré charakterizuje konfiguračný súbor a mena súboru.
Každý z ôsmych znakov popisuje výsledok porovnania jedného konkrétneho
atribútu súboru s údajmi zaznamenanými v RPM databáze. Jednoduchá "\fB.\fP"
(bodka) znamená, že test prešiel (neobjavené žiadne odchýľky).
Nasledujúce znaky oznamujú dôvod neúspechu určitého testu:

.IP "\fB5\fP"
MD5 kontrolný súčet
.IP "\fBS\fP"
Veľkosť súboru
.IP "\fBL\fP"
Symbolický link
.IP "\fBT\fP"
Mtime (posledný čas modifikácie)
.IP "\fBD\fP"
Zariadenie
.IP "\fBU\fP"
Užívateľ
.IP "\fBG\fP"
Skupina
.IP "\fBM\fP"
Mód (vrátane oprávnení a typu súborov)


.SH KONTROLA PODPISOV (SIGNATURE)
Všeobecná forma príkazu kontroly rpm podpisu je
.PP
	\fBrpm \-\-checksig \fI<súbor_balíka>+\fP
.PP
Takto sa overuje PGP podpis balíka \fI<súbor_balíka>\fP na uistenie
sa o jeho integrite a pôvode.
Konfiguračné informácie PGP sú čítané z konfiguračných súborov.
Bližšie údaje sa nachádzajú v sekcii PGP POPDPISY.


.SH VOĽBY PRI ODINŠTALÁCII
Všeobecná forma príkazu na odinštalovanie je
.PP
	\fB    rpm \-e \fI<meno_balíka>+\fP
.PP
.IP "\fB\-\-allmatches\fP"
Odstráni všetky verzie balíka, ktoré súhlasia s menom \fI<meno_balíka>\fR.
Normálne sa vyvolá chyba, ak viac balíkov súhlasí s menom
\fI<meno_balíka>\fR.
.IP "\fB\-\-noscripts\fP"
Nevykoná pred a po odinštalačné skripty.
.IP "\fB\-\-notriggers\fP"
Nevykoná skripty, ktorých spúšťou je odinštalovanie balíka.
.IP "\fB\-\-nodeps\fP"
Nebude skúmať závislosti pri odinštalovaní balíkov.
.IP "\fB\-\-test\fP"
Nič sa v skutočnosti neodinštaluje, len sa preverí, čo by sa malo stať.
Veľmi užitočné s voľbou \fB\-vv\fP.


.SH VOĽBY PRI ZOSTAVOVANÍ
Všeobecná forma príkazu na zostavenie rpm je
.PP
    \fBrpm \-[b|t]\fIO\fP [zostavovacie\-voľby] \fI<spec_súbor_balíka>+\fP
.PP
Argumentom je \fB-b\fR, ak sa na zostavenie balíka použije spec súbor
(súbor špecifikácií balíka) alebo \fB-t\fR, ak \fBRPM\fR má vyhľadať
spec súbor vnútri gzipovaného (alebo komprimovaného) tar archívu, a tento
použiť na zostavenie balíka. Po prvom argumente ďaľší argument (\fIO\fR)
špecifikuje fázu štádia zostavenia a zabalenia, ktorá sa má vykonať, a
ktorá je jedna z:

.IP "\fB\-bp\fP"
Vykoná "%prep" fázu pre spec súbor. Normálne toto vyvolá rozbalenie
zdrojových archívov a aplikovanie záplat.
.IP "\fB\-bl\fP"
Vykoná "kontrolu zoznamu". Sekcia "%files" z spec súboru je makrom
expandovaná, a je vykonaná kontrola, že každý súbor existuje.
.IP "\fB\-bc\fP"
Vykoná fázu "%build" pre spec súbor (po vykonaní prep fázy). Toto
normálne vyvolá ekvivalent príkazu "make".
.IP "\fB\-bi\fP"
Vykoná fázu "%install" zo spec súboru (po vykonaní prep a build fázy).
Toto vo všeobecnosti vyvolá ekvivalent príkazu "make install".
.IP "\fB\-bb\fP"
Zostaví binárny balík (po vykonaní prep, build a install fázy).
.IP "\fB\-bs\fP"
Zostaví iba zdrojový balík (po vykonaní prep, build a install fázy).
.IP "\fB\-ba\fP"
Zostaví binárny a zdrojový balík (po vykonaní prep, build a install fázy).
.PP
Môžu byť použité aj nasledujúce voľby:
.IP "\fB\-\-short\-circuit\fP"
Preskočí priamo na požadovanú fázu (t. zn. preskočí všetky fázy štádia
zostavenia, ktoré predchádzajú špecifikovanej fáze). Táto voľba je platná
iba s prepínačmi \fB\-bc\fP and \fB\-bi\fP.
.IP "\fB\-\-timecheck\fP"
Nastavuje "kontrolu času" (0 zakáže). Táto voľba môže byť nastavená
definovaním makra "_timecheck". Hodnota "kontroly času" vyjadruje
(v sekundách) maximálny vek súborov, ktoré budú zabalené. Varovania
sú vypisované pre všetky súbory, ktorých vek je za hranicou takto
definovanej hodnoty.
.IP "\fB\-\-clean\fP"
Odstrání zostavovací strom (adresár) potom, čo sa vytvorí balík.
.IP "\fB\-\-rmsource\fP"
Odstrání zdrojové súbory a spec súbor po zostavení (môže sa používať aj
samostatne, napr. "\fBrpm \-\-rmsource foo.spec\fP").
.IP "\fB\-\-test\fP"
Nevykoná žiadnu zo zostavovacej fázy.
Užitočné pre otestovanie spec súboru.
.IP "\fB\-\-sign\fP"
Vloží PGP podpis do balíka. Tento podpis môže byť využitý na overenie
integrity a pôvodu balíka. Bližšie informácie na nastavenie sú uvedené
v sekcii PGP PODPISY.
.IP "\fB\-\-buildroot \fI<adresár>\fP"
Pri zostavovaní balíka prepíše tag BuildRoot adresárom \fI<adresár>\fP.
.IP "\fB\-\-target \fI<platforma>\fP"
Pri zostavovaní balíka sa interpretuje \fI<platforma>\fP ako
\fBarch-vendor-os\fP a makrá \fB_target\fP, \fB_target_arch\fP a
\fB_target_os\fP sa nastavia podľa tejto hodnoty.


.SH VOĽBY PRI ZNOVUZOSTAVOVANÍ A REKOMPILOVANÍ

Existujú dve voľby, ako spustiť zostavenie balíka s rpm:

.I "\fBrpm \-\-recompile \fI<zdrojový_súbor_balíka>+\fP"

.I "\fBrpm \-\-rebuild \fI<zdrojový_súbor_balíka>+\fP"

Keď je rpm spustené týmto spôsobom, \fBrpm\fP nainštaluje zdrojový balík a
vykoná postupne fázy prípravy (prep), kompilácie a inštalácie. Prídavne
s voľbou \fB\-\-rebuild\fP zostaví nový binárny balík. Keď sa zostavenie
dokončí, adresár zostavovania (ako pri \fB\-\-clean\fP), zdrojové súbory,
ako aj spec súbor sa sa odstránia.


.SH PODPISOVANIE EXISTUJÚCEHO RPM

.I "\fBrpm \-\-resign \fI<binárny_súbor_balíka>+\fP"

Táto voľba vygeneruje a vloží nový podpis pre zoznam balíkov.
Všetky prípadne existujúce podpisy sa odstránia.

.I "\fBrpm \-\-addsign \fI<binárny_súbor_balíka>+\fP"

Táto voľba vygeneruje a pridá nový podpis pre zoznam balíkov u ktorých
už podpis existuje.


.SH PGP PODPISY

Aby bolo možné používať vlastnosti podpisovania, RPM je potrebné nastaviť
spôsobom, aby mohlo spúšťať PGP, a aby bolo schopné nájsť zväzok verejných
kľúčov s RPM verejnými kľúčmi v ňom. Implicitne RPM používa implicitné
hodnoty PGP na nájdenie zväzkov kľúčov (honorujúc PGPPATH).
Ak je zväzok kľúčov umiestnený na inom mieste, ako PGP očakáva, je potrebné
nastaviť makro

.IP "\fB_pgp_path\fP"
na definovanie umiestnenia zväzkov kľúčov PGP, ktoré sa majú použiť.
.PP

Ak si želáte podpisovať balíky, ktoré si sami vytvoríte, potrebujete
podobným spôsobom vytvoriť váš verejný a tajný kľúčový pár (bližšie informácie
sú v dokumentácii ku PGP).
Taktiež potrebujete konfigurovať makrá:

.IP "\fB_pgp_name\fP"
Meno "užívateľa", ktorého kľúčom sa má podpísať balík.
.PP

Pri zostavovaní balíka je potrebné pridať \-\-sign do príkazového
riadku. Nasledovne sa objaví výzva na heslo, a po správnom zadadaní
sa balík zostaví a podpíše.

Napríkad pre použitie PGP na podpísanie balíka ako užívateľ
\fB"John Doe <jdoe@foo.com>"\fP zo zväzku kľúčov umiestnených
v \fB/etc/rpm/.pgp\fP použitím \fB/usr/bin/pgp\fP zápis bude
obsahovať

.I "\fB%_pgp_path /etc/rpm/.pgp\fP"

.I "\fB%_pgp_name John Doe <jdoe@foo.com>\fP"

.I "\fB%_pgpbin /usr/bin/pgp\fP"

v konfiguračnom súbore makier: \fB/etc/rpm/macros\fP je určený na
per-systém nastavenie a \fB~/.rpmmacros\fP na per-užívateľ nastavenie.


.SH VOĽBY PRI PREBUDOVANÍ DATABÁZY
Všeobecná forma príkazu prebudovania databázy je
.PP
	\fBrpm \-\-rebuilddb\fP
.PP

Na vybudovanie novej databázy treba vykonať
.PP
	\fBrpm \-\-initdb\fP
.PP

Jedinými voľbami pre tento režim sú \fB-\-dbpath\fP a \fB-\-root\fP.


.SH SHOWRC 

Spustením 

.PP
	\fBrpm \-\-showrc\fP

.PP
sa vypíšu hodnoty, ktoré bude RPM používať pri všetkých voľbách, a
ktoré môžu byť nastavené v \fIrpmrc\fP súboroch.


.SH FTP/HTTP VOĽBY

RPM obsahuje jednoduchého FTP a HTTP klienta na zjednodušenie inštalácie
a jednoduchšieho získania informácií balíkov, ktoré sú umiestenené na sieti.
Súbory balíkov určené pre inštalovanie, aktualizáciu a výpis informácií je
možné špecifikovať v ftp alebo http štýle URL:

.PP
	\fBftp://<užívateľ>:<heslo>@počítač:<port>/path/to/package.rpm\fP
.PP
Ak časť \fB:heslo\fP chýba, objaví sa výzva na heslo (vždy len jeden krát
pre pár užívateľ/počítač). Ak chýbajú obe časti - užívateľ aj heslo, použitý
je anonymný ftp. Vo všetkých prípadoch je použitý pasívny (PASV) ftp prenos.

RPM povoluje použiť nasledujúce voľby s ftp URL:

.IP "\fB\--ftpproxy \fI<meno_počítača>\fP"
Počítač \fI<meno_počítača>\fP sa použije ako proxy server pre všetky ftp
prenosy, čo umožní užívateľom použiť ftp služby za firewallom, ktorý
používa proxy systémy.
Táto voľba môže byť tak isto špecifikovaná nastavením makra \fB_ftpproxy\fP.

.IP "\fB\--ftpport \fI<port>\fP"
Použije sa číslo TCP portu \fI<port>\fP pre ftp spojenie s ftp proxy
serverom namiesto implicitného portu. Táto voľba môže byť tak isto
špecifikovaná nastavením makra \fB_ftpport\fP.
.PP

RPM umožňuje nasledujúce voľby pri použití http URL:

.IP "\fB\--httpproxy \fI<meno_počítača>\fP"
Počítač \fI<meno_počítača>\fP bude použitý ako proxy server pre všetky http
prenosy.
Táto voľba môže byť tak isto špecifikovaná konfigurovaním makra
\fB_httpproxy\fP.

.IP "\fB\--httpport \fI<port>\fP"
Použije sa číslo TCP portu \fI<port>\fP pre http spojenie s http proxy
serverom namiesto implicitného portu.
Táto voľba môže byť tiež špecifikovaná konfigurovaním makra
\fB_httpport\fP.
.PP


.SH SÚBORY
.nf
/usr/lib/rpm/rpmrc
/etc/rpmrc
~/.rpmrc
/usr/lib/rpm/macros
/etc/rpm/macros
~/.rpmmacros
/var/lib/rpm/conflictsindex.rpm
/var/lib/rpm/fileindex.rpm
/var/lib/rpm/groupindex.rpm
/var/lib/rpm/nameindex.rpm
/var/lib/rpm/packages.rpm
/var/lib/rpm/providesindex.rpm
/var/lib/rpm/requiredby.rpm
/var/lib/rpm/triggerindex.rpm
/tmp/rpm*
.fi
.SH PRÍBUZNÁ DOKUMENTÁCIA 
.IR glint (8) ,
.IR rpm2cpio (8) ,
.B http://www.rpm.org/
.nf
.SH AUTORI
.nf
Marc Ewing <marc@redhat.com>
Jeff Johnson <jbj@redhat.com>
Erik Troan <ewt@redhat.com>
.fi
