#!/bin/sh

top_builddir="$1"
abs_builddir="$2"
srcdir="$3"
bindir="$4"
MAKE="$5"
tree=tree

# The chmod is needed when copying from read-only sources (eg in distcheck)
if [ -d ${tree} ]; then
	chmod -R u+w ${tree}/;
fi
rm -rf ${tree}

mkdir -p ${tree}/${bindir}
ln -s ./${bindir} ${tree}/bin
mkdir -p ${tree}/usr
if [ ! -d ${tree}/usr/bin ]; then
	ln -s ../bin ${tree}/usr/bin
fi

(cd ${top_builddir} && \
	  ${MAKE} DESTDIR=${abs_builddir}/${tree} install)

cp -r ${srcdir}/data/ ${tree}/
for d in dev etc magic tmp var; do
	if [ ! -d ${tree}/${d} ]; then
		mkdir ${tree}/${d}
	fi
done
for node in urandom stdin stderr stdout null full; do
	ln -s /dev/${node} ${tree}/dev/${node}
done
for cf in hosts resolv.conf passwd group mtab ; do
	[ -f /etc/${cf} ] && cp /etc/${cf} ${tree}/etc/${cf}
done
touch ${tree}/etc/{shadow,gshadow}
for prog in gzip cat cp patch tar sh bash ln chmod rm mkdir uname grep sed find file ionice mktemp nice cut sort diff touch install wc coreutils xargs mknod locale systemd-sysusers true false; do
	p=`which ${prog}`
	if [ "${p}" != "" ]; then
		ln -s ${p} ${tree}/${bindir}/
	fi
done
for d in /proc /sys /selinux /etc/selinux; do
	if [ -d ${d} ]; then
		ln -s ${d} ${tree}/${d}
	fi
done
(cd ${tree}/magic && cp /usr/share/misc/magic.mgc . || file -C)
