.TH lsbpkgchk "1" "" "lsbpkgchk (LSB)" LSB
.SH NAME
lsbpkgchk \- check LSB conformance of a package
.SH SYNOPSIS
.B lsbpkgchk
[\f-L \fIpathtolib\fR]... [\fIappname\fR]...
.SH DESCRIPTION
.PP
Measure a package's conformance to the Linux Standard
Base (LSB) specification. The format of the package, and the contents of the
payload are checked.  Warnings are produced for anything that is used, but not
contained in the LSB specification.
.PP
A journal file named journal.pkgchk> is created. It contains a record of the
test results. You must have write access to the current working directory
in order to run lsbpkgchk successfully.
.SH "AUTHORS"
The contributors to the Linux Standard Base.
.SH "REPORTING BUGS"
Report bugs to <lsb-test@linuxbase.org>.
.SH "BUGS"
Should be able to specify where to write the journal file.
.SH "SEE ALSO"
Linux Standard Base specification and other documents at
http://www.linuxbase.org/
