$set 1 # Automatically created from de.gmo by gmo2msg
# Date: 2001-10-06 20:40:10+0200
# From: Michael Riepe <michael@thrai>
# Content-Type: text/plain; charset=iso-8859-1
# Xgettext-Options: -c -dlibelf -k_
# Files: ../lib/errors.h
#
$ Original message: no error
1 Kein Fehler
#
$ Original message: unknown error
2 Unbekannter Fehler
#
$ Original message: Internal error: unknown reason
3 Interner Fehler: Ursache unbekannt
#
$ Original message: Internal error: not implemented
4 Interner Fehler: diese Funktion ist nicht implementiert
#
$ Original message: Request error: cntl(ELF_C_FDREAD) on write-only file
5 Aufruffehler: cntl(ELF_C_FDREAD) ohne Leseberechtigung
#
$ Original message: Request error: invalid ELF_C_* argument
6 Aufruffehler: das ELF_C_*-Argument ist ungültig
#
$ Original message: Request error: file descriptor disabled
7 Aufruffehler: der Zugriff auf diese Datei ist nicht mehr möglich
#
$ Original message: Request error: not an archive
8 Aufruffehler: die bearbeitete Datei ist kein Archiv (.a)
#
$ Original message: Request error: offset out of range
9 Aufruffehler: die gewünschte Byteposition liegt außerhalb der Datei
#
$ Original message: Request error: unknown ELF version
10 Aufruffehler: unbekannte ELF-Version
#
$ Original message: Request error: ELF_C_* argument does not match
11 Aufruffehler: das ELF_C_*-Argument paßt nicht zu den Zugriffsrechten
#
$ Original message: Request error: archive member begin() for writing
12 Aufruffehler: der Archivinhalt ist nicht schreibbar
#
$ Original message: Request error: archive/member file descriptor mismatch
13 Aufruffehler: die Datei- und Archiv-Deskriptoren passen nicht zusammen
#
$ Original message: Request error: not an ELF file
14 Aufruffehler: dies ist kein ELF-Datei
#
$ Original message: Request error: class file/memory mismatch
15 Aufruffehler: die Datei gehört zur falschen ELF-Klasse (32/64 Bit)
#
$ Original message: Request error: invalid ELF_T_* argument
16 Aufruffehler: das ELF_T_*-Argument ist ungültig
#
$ Original message: Request error: unknown data encoding
17 Aufruffehler: unbekannte Datenrepräsentation (big/little endian)
#
$ Original message: Request error: destination buffer too small
18 Aufruffehler: der Zielpuffer ist zu klein
#
$ Original message: Request error: d_buf is NULL
19 Aufruffehler: d_buf ist ein NULL-Zeiger
#
$ Original message: Request error: unknown ELF class
20 Aufruffehler: unbekannte ELF-Klasse (32/64 Bit)
#
$ Original message: Request error: section does not belong to file
21 Aufruffehler: der Dateiabschnitt gehört nicht zu dieser Datei
#
$ Original message: Request error: no section at index
22 Aufruffehler: ein Abschnitt mit dieser Nummer existiert nicht
#
$ Original message: Request error: can't manipulate null section
23 Aufruffehler: Sie versuchen, den "Null"-Abschnitt zu bearbeiten
#
$ Original message: Request error: data does not belong to section
24 Aufruffehler: dieser Datenblock gehört nicht zum angegebenen Dateiabschnitt
#
$ Original message: Request error: no string table
25 Aufruffehler: die Namenliste fehlt
#
$ Original message: Request error: string table offset out of range
26 Aufruffehler: die gewünschte Position liegt außerhalb der Namenliste
#
$ Original message: Request error: update(ELF_C_WRITE) on read-only file
27 Aufruffehler: update(ELF_C_WRITE) ohne Schreibberechtigung
#
$ Original message: I/O error: seek
28 Ein-/Ausgabefehler: das Positionieren innerhalb der Datei schlug fehl
#
$ Original message: I/O error: file too big for memory
29 Ein-/Ausgabefehler: die Datei ist zu groß
#
$ Original message: I/O error: raw read
30 Ein-/Ausgabefehler: Lesefehler
#
$ Original message: I/O error: get file size
31 Ein-/Ausgabefehler: die Dateigröße ist nicht zu ermitteln
#
$ Original message: I/O error: output write
32 Ein-/Ausgabefehler: Schreibfehler
#
$ Original message: I/O error: can't truncate output file
33 Ein-/Ausgabefehler: das Verkürzen der Datei schlug fehl
#
$ Original message: Sequence error: must set ELF version first
34 Falsche Reihenfolge: Sie müssen zuerst elf_version() aufrufen
#
$ Original message: Sequence error: must create ELF header first
35 Falsche Reihenfolge: Sie müssen zuerst elf{32,64}_newehdr() aufrufen
#
$ Original message: Format error: reference outside file
36 Fehler in der Datei: eine Positionsangabe zeigt auf einen Punkt außerhalb der Datei
#
$ Original message: Format error: archive header truncated
37 Fehler in der Datei: der Archiv-Header ist unvollständig
#
$ Original message: Format error: archive fmag
38 Fehler in der Datei: die Archiv-Kennung ist falsch
#
$ Original message: Format error: archive header
39 Fehler in der Datei: der Archiv-Header ist fehlerhaft
#
$ Original message: Format error: archive member truncated
40 Fehler in der Datei: der Archivinhalt ist unvollständig
#
$ Original message: Format error: archive symbol table size
41 Fehler in der Datei: die Größe der Archiv-Symboltabelle ist falsch
#
$ Original message: Format error: archive string table
42 Fehler in der Datei: die Archiv-Namenliste ist defekt
#
$ Original message: Format error: archive special name unknown
43 Fehler in der Datei: es existiert ein internes Archiv-Objekt mit unbekanntem Namen
#
$ Original message: Format error: ELF header truncated
44 Fehler in der Datei: der ELF-Header ist unvollständig
#
$ Original message: Format error: program header table truncated
45 Fehler in der Datei: die ELF Program Header Table ist unvollständig
#
$ Original message: Format error: section header table truncated
46 Fehler in der Datei: die ELF Section Header Table ist unvollständig
#
$ Original message: Format error: data region truncated
47 Fehler in der Datei: ein Datenblock ist unvollständig
#
$ Original message: Format error: program header table alignment
48 Fehler in der Datei: die ELF Program Header Table liegt nicht auf einer Wortgrenze
#
$ Original message: Format error: section header table alignment
49 Fehler in der Datei: die ELF Section Header Table liegt nicht auf einer Wortgrenze
#
$ Original message: Format error: bad parameter in Verdef record
50 Fehler in der Datei: Verdef-Datensatz enthält ungültige Parameter
#
$ Original message: Format error: unknown Verdef version
51 Fehler in der Datei: libelf unterstützt die Verdef-Version nicht
#
$ Original message: Format error: bad parameter in Verneed record
52 Fehler in der Datei: Verneed-Datensatz enthält ungültige Parameter
#
$ Original message: Format error: unknown Verneed version
53 Fehler in der Datei: libelf unterstützt die Verneed-Version nicht
#
$ Original message: Layout error: section size too small for data
54 Layout-Fehler: ein Dateiabschnitt ist zu kurz für die darin enthaltenen Daten
#
$ Original message: Layout error: overlapping sections
55 Layout-Fehler: zwei (oder mehr) Dateiabschnitte überlappen sich
#
$ Original message: Memory error: elf descriptor
56 Zu wenig Speicher: für den Elf-Deskriptor
#
$ Original message: Memory error: archive symbol table
57 Zu wenig Speicher: für die Archiv-Symboltabelle
#
$ Original message: Memory error: archive member header
58 Zu wenig Speicher: für die Archiv-Verwaltungsinformationen
#
$ Original message: Memory error: ELF header
59 Zu wenig Speicher: für den ELF-Header
#
$ Original message: Memory error: program header table
60 Zu wenig Speicher: für die Program Header Table
#
$ Original message: Memory error: section header table
61 Zu wenig Speicher: für die Section Header Table
#
$ Original message: Memory error: section descriptor
62 Zu wenig Speicher: für den Elf_Scn-Deskriptor
#
$ Original message: Memory error: section data
63 Zu wenig Speicher: für die Daten dieses Abschnitts
#
$ Original message: Memory error: output file space
64 Zu wenig Speicher: für die Ausgabe
#
$ Original message: GElf error: value out of range
65 GElf-Fehler: eine Zahl ist außerhalb des darstellbaren Bereichs
#
$ Original message: GElf error: index out of range
66 GElf-Fehler: Index außerhalb des erlaubten Bereichs
#
$ Original message: GElf error: type mismatch
67 GElf-Fehler: Typfehler
#
$ Original message: GElf error: not enough memory for GElf_Sym
68 GElf-Fehler: zu wenig Speicher für eine Variable vom Typ GElf_Sym
#
$ Original message: GElf error: not enough memory for GElf_Dyn
69 GElf-Fehler: zu wenig Speicher für eine Variable vom Typ GElf_Dyn
#
$ Original message: GElf error: not enough memory for GElf_Rela
70 GElf-Fehler: zu wenig Speicher für eine Variable vom Typ GElf_Rela
#
$ Original message: GElf error: not enough memory for GElf_Rel
71 GElf-Fehler: zu wenig Speicher für eine Variable vom Typ GElf_Rel
