#!/bin/sh -
#	$Id: testall,v 12.0 2004/11/17 03:44:48 bostic Exp $
#
# Run all the C++ regression tests

ecode=0
prefixarg=""
stdinarg=""
while :
do
	case "$1" in
	--prefix=* )
		prefixarg="$1"; shift;;
	--stdin )
		stdinarg="$1"; shift;;
	* )
		break
	esac
done
files="`find . -name \*.cpp -print`"
for file in $files; do
	name=`echo $file | sed -e 's:^\./::' -e 's/\.cpp$//'`
	if grep $name ignore > /dev/null; then
		echo "    **** cxx test $name ignored"
	else
		echo "    ==== cxx test $name"
		if ! sh ./testone $prefixarg $stdinarg $name; then
			ecode=1
		fi
	fi
done
exit $ecode
