.\" Jakub Bogusz <qboosh@pld-linux.org>, 2003
.\" rpm 4.3-20030610
.TH "RPMGRAPH" "8" "30 czerwca 2002" "Red Hat, Inc."
.SH NAZWA
rpmgraph \- Wyświetlanie grafu zależności pakietu RPM
.SH SKŁADNIA
.PP

\fBrpmgraph\fR \fB\fIPLIK_PAKIETU\fB\fR\fI ...\fR

.SH "OPIS"
.PP
\fBrpmgraph\fR używa argumentów \fIPLIK_PAKIETU\fR do wygenerowania
grafu zależności pakietów. Każdy argument \fIPLIK_PAKIETU\fR jest
czytany i dodawany do zbioru transakcji rpm-a. Elementy zbioru
transakcji są częściowo porządkowane przy użyciu sortowania
topologicznego. Następnie częściowo uporządkowane elementy są
wypisywane na standardowe wyjście.
.PP
Wierzchołki w grafie zależności to nazwy pakietów, krawędzie w grafie
skierowanym wskazują na rodzica każdego wierzchołka. Rodzic jest
zdefiniowany jako ostatni poprzednik pakietu w częściowym porządku
przy użyciu gdzie zależności pakietu jako relacji. Oznacza to, że
rodzic danego pakietu jest ostatnią zależnością pakietu.
.PP
Wyjście jest w formacie grafu skierowanego \fBdot\fR(1) i może być
wyświetlone lub wydrukowane przy użyciu edytora grafów \fBdotty\fR
z pakietu \fBgraphviz\fR.
Nie ma opcji specyficznych dla programu \fBrpmgraph\fR, tylko wspólne
opcje \fBrpm\fR-a. Aktualnie zaimplementowane opcje można zobaczyć
w komunikacie o składni komendy \fBrpmgraph\fR.
.SH "ZOBACZ TAKŻE"

\fBdot\fR(1),

\fBdotty\fR(1),

\fB http://www.graphviz.org/ <URL:http://www.graphviz.org/>
\fR
.SH "AUTORZY"

Jeff Johnson <jbj@redhat.com>
