.\" rpm2cpio - конвертирует пакет RPM в архив cpio
.TH rpm2cpio 8 "25 февраля 2006" "Инвента"
.SH НАЗВАНИЕ
rpm2cpio \-  Извлекает архив cpio из RPM пакета
.SH ОБЗОР
\fBrpm2cpio\fP [имя файла] 
.SH ОПИСАНИЕ
\fBrpm2cpio\fP конвертирует файл .rpm, заданный как его единственный аргумент,
в архив cpio на стандартном выводе. Если в качестве аргумента указано '-', 
RPM пакет считывается со стандартного ввода.

.br
.I "\fBrpm2cpio rpm-1.1-1.i386.rpm\fP"
.br
.I "\fBrpm2cpio - < glint-1.0-1.i386.rpm\fP"
.br
.I "\fBrpm2cpio glint-1.0-1.i386.rpm | cpio -dium\fP"

.SH СМОТРИ ТАКЖЕ
.IR rpm (8)
.SH АВТОР
.nf
Erik Troan <ewt@redhat.com>
.fi
.SH ПЕРЕВОД
.nf
Андрей Мартынов <andrewm@inventa.ru>
.fi
