'\" t
.TH "RPM-AUDIT" "8" "28 Jan 2020" "Red Hat, Inc."
.SH NAME
rpm-plugin-audit \- Audit plugin for the RPM Package Manager

.SH Description

The plugin writes basic information about rpm transactions to the
audit log - like packages installed or removed. The entries can be
viewed with

.B ausearch -m SOFTWARE_UPDATE


.SS Data fields

The entries in the audit log have the following fields:

.TP
.B Field
.B Possible values		Description

.TP
.B op
install/update/remove	package operation

.TP
.B sw
name-version-release.arch of the package
.TP
.B key_enforce
0/1	are signatures being enforced
.TP
.B gpg_res
0/1	result of signature check (0 == fail / 1 ==success)
.TP
.B root_dir
Root directory of the operation, normally "/"
.TP
.B sw_type
"rpm"	package format


.SH Configuration

There are currently no options for this plugin in particular. See
.BR rpm-plugins (8)
on how to control plugins in general.

.SH SEE ALSO
.IR ausearch (8)
.IR rpm-plugins (8)
