'\" t
.TH "RPM-FAPOLICYD" "8" "28 Jan 2021" "Red Hat, Inc."
.SH NAME
rpm-plugin-fapolicyd \- Fapolicyd plugin for the RPM Package Manager

.SH Description

The plugin gathers metadata of currently installed files. It sends the
information about files and about ongoing rpm transaction to the fapolicyd daemon.
The information is written to Linux pipe which is placed in
/var/run/fapolicyd/fapolicyd.fifo.

.SH Configuration

There are currently no options for this plugin in particular. See
.BR rpm-plugins (8)
on how to control plugins in general.

.SH SEE ALSO
.IR fapolicyd (8)
.IR rpm-plugins (8)
