.TH "RPMSPEC" "8" "29 October 2010" "Red Hat, Inc"
.SH NAME
rpmspec \- RPM Spec Tool
.SH SYNOPSIS
.SS "QUERYING SPEC FILES:"
.PP

\fBrpmspec\fR {\fB-q|--query\fR} [\fBselect-options\fR] [\fBquery-options\fR] \fB\fISPEC_FILE\fB\fR\fI ...\fR

.SS "select-options"
.PP

 [\fB\--rpms\fB\fR]
 [\fB\--srpms\fB\fR]

.SS "query-options"
.PP

 [\fB--qf,--queryformat \fIQUERYFMT\fB\fR]
 [\fB--target \fITARGET_PLATFORM\fB\fR]
 
.SS "QUERY OPTIONS"
.PP
The general form of an rpm spec query command is 
.PP

\fBrpm\fR {\fB-q|--query\fR} [\fBselect-options\fR] [\fBquery-options\fR]

.PP
You may specify the format that the information should be
printed in. To do this, you use the

 \fB--qf|--queryformat\fR \fB\fIQUERYFMT\fB\fR

option, followed by the \fIQUERYFMT\fR format string.
See \fBrpm(8)\fR for details.
.PP

.SS "SELECT OPTIONS"
.PP
 \fB--rpms\fR
Operate on the binary package header(s).
 \fB--srpm\fR
Operate on the source package header(s).

.SH "SEE ALSO"
.nf
\fBpopt\fR(3),
\fBrpm\fR(8),
\fBrpmdb\fR(8),
\fBrpmkeys\fR(8),
\fBrpmsign\fR(8),
\fBrpm2cpio\fR(8),
\fBrpmbuild\fR(8),
.fi

\fBrpmspec --help\fR - as rpm supports customizing the options via popt aliases 
it's impossible to guarantee that what's described in the manual matches 
what's available.


\fBhttp://www.rpm.org/ <URL:http://www.rpm.org/>
\fR
.SH "AUTHORS"

.nf
Marc Ewing <marc@redhat.com>
Jeff Johnson <jbj@redhat.com>
Erik Troan <ewt@redhat.com>
Panu Matilainen <pmatilai@redhat.com>
.fi
