.\" rpm2cpio - Converts Red Hat Package (RPM) to cpio archive
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation; either version 2, or (at your option)
.\" any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program; if not, write to the Free Software
.\" Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, 
.\" USA.
.\"
.\" Japanese Version Copyright (C) 2003 System Design and Research
.\" Institute Co.,Ltd. All rights reserved.
.\"
.\" Translated 14 March 2003 by
.\"   System Design and Research Institute Co.,Ltd. <info@sdri.co.jp>
.\"
.TH rpm2cpio 8 "11 January 2001" "Red Hat, Inc."
.SH 名前
rpm2cpio \- RPM (RPM Package Manager)パッケージから cpio アーカイブを
抽出する
.SH 書式
\fBrpm2cpio\fP [filename] 
.SH 説明
.B rpm2cpio
は引数で指定される一つの .rpm ファイルを cpio アーカイブ形式に変換し、
標準出力に出力する。
引数に '\-' が指定された場合には、標準入力から rpm を読み込む。
.PP
.br
.B "rpm2cpio rpm-1.1-1.i386.rpm"
.br
.B "rpm2cpio \- < glint-1.0-1.i386.rpm"
.br
.B "rpm2cpio glint-1.0-1.i386.rpm | cpio -dium"
.SH 関連項目
.IR rpm (8)
.SH 著者
.nf
Erik Troan <ewt@redhat.com>
.fi
