.\"
.\" librsync -- dynamic caching and delta update in HTTP
.\" Id: codeheader.man,v 1.1 2002/01/25 21:25:34 bje Exp 
.\" 
.\" Copyright (C) 2000 by Martin Pool <mbp@humbug.org.au>
.\" 
.\" This program is free software; you can redistribute it and/or
.\" modify it under the terms of the GNU Lesser General Public License
.\" as published by the Free Software Foundation; either version 2.1 of
.\" the License, or (at your option) any later version.
.\" 
.\" This program is distributed in the hope that it will be useful, but
.\" WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
.\" Lesser General Public License for more details.
.\" 
.\" You should have received a copy of the GNU Lesser General Public
.\" License along with this program; if not, write to the Free Software
.\" Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"

.TH librsync 2 "Date: 2002/01/25 21:25:34 " 
.SH NAME
.SH SYNOPSYS
.SH DESCRIPTION
.SH "RETURN VALUE"
.SH "SEE ALSO"
