#!/bin/sh
#---------------------------------------------------------------
# Origin	: Linux-Mandrake
# Author	: Frederic Lepied
# Created On	: Tue Nov  7 08:33:05 2000
# Description	: Run ldconfig to create symlinks to libraries.
#
# Copyright (C) 2000 by Frederic Lepied <flepied@mandrakesoft.com>
# Redistribution of this file is permitted under the terms of the GNU
# Public License (GPL).
#---------------------------------------------------------------

# If using normal root, avoid changing anything.
if [ -z "$RPM_BUILD_ROOT" -o "$RPM_BUILD_ROOT" = "/" ]; then
	exit 0
fi

libs=`find "$RPM_BUILD_ROOT" -type d \
   -a "(" -name lib -o -name lib64 ")" \
   -a ! "(" -path '*/usr/src/debug*' -o -path '*/usr/lib/debug*' ")" \
   `

if [ -n "$libs" -o -n "$EXTRA_LIBS_TO_SYMLINK" ]; then
    /sbin/ldconfig -n -N $libs $EXTRA_LIBS_TO_SYMLINK
fi
