#!/bin/sh

# If using normal root, avoid changing anything.
if [ -z "$RPM_BUILD_ROOT" -o "$RPM_BUILD_ROOT" = "/" ]; then
	exit 0
fi

cd "$RPM_BUILD_ROOT"

# Compress man pages
COMPRESS=${COMPRESS:-gzip -9 -n}
COMPRESS_EXT=${COMPRESS_EXT:-.gz}

ROOT_PREFIX=${1:-.}
if [ "${ROOT_PREFIX%%/*}" != "." ]; then
    echo "$0: Prefix $ROOT_PREFIX must start with ./"
    exit 1
fi

for d in ${ROOT_PREFIX}/usr/man/man* ${ROOT_PREFIX}/usr/man/*/man* ${ROOT_PREFIX}/usr/info \
	${ROOT_PREFIX}/usr/share/man/man* ${ROOT_PREFIX}/usr/share/man/*/man* ${ROOT_PREFIX}/usr/share/info \
	${ROOT_PREFIX}/usr/kerberos/man ${ROOT_PREFIX}/usr/X11R6/man/man* ${ROOT_PREFIX}/usr/lib/perl5/man/man* \
	${ROOT_PREFIX}/usr/share/doc/*/man/man* ${ROOT_PREFIX}/usr/lib/*/man/man*
do
    [ -d $d ] || continue
    for f in `find $d -type f ! -name dir`
    do
        [ -f "$f" ] || continue

	case "$f" in
	 *.gz|*.Z)    gunzip  -f $f; b=`echo $f | sed -e 's/\.\(gz\|Z\)$//'`;;
	 *.bz2)       bunzip2 -f $f; b=`echo $f | sed -e 's/\.bz2$//'`;;
	 *.xz|*.lzma) unxz    -f $f; b=`echo $f | sed -e 's/\.\(xz\|lzma\)$//'`;;
	 *) b=$f;;
	esac

	$COMPRESS $b </dev/null 2>/dev/null || {
	    inode=`ls -i $b | awk '{ print $1 }'`
	    others=`find $d -type f -inum $inode`
	    if [ -n "$others" ]; then
		for afile in $others ; do
		    [ "$afile" != "$b" ] && rm -f $afile
		done
		$COMPRESS -f $b
		for afile in $others ; do
		    [ "$afile" != "$b" ] && ln $b$COMPRESS_EXT $afile$COMPRESS_EXT
		done
	    else
		$COMPRESS -f $b
	    fi
	}
    done

    for f in `find $d -type l`
    do
	l=`ls -l $f | sed -e 's/.* -> //' -e 's/\.\(gz\|Z\|bz2\|xz\|lzma\)$//'`
	rm -f $f
	b=`echo $f | sed -e 's/\.\(gz\|Z\|bz2\|xz\|lzma\)$//'`
	ln -sf $l$COMPRESS_EXT $b$COMPRESS_EXT
    done
done
