#! /bin/sh

# Copyright (C) 2004 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
#  
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License.
#  
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#  
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA


test -z "$QA_SKIP_BUILD_ROOT" || exit 0

if [ -z "$RPM_BUILD_ROOT" ] || [ "$RPM_BUILD_ROOT" = "/" ]; then
        exit 0
fi

tmp="$(mktemp "${TMPDIR:-/tmp}"/cbr.XXXXXX)"
[ -w "$tmp" ] || exit 1
trap 'rm -f "$tmp"' EXIT

NCPUS=${RPM_BUILD_NCPUS:-1}

export LANG=C
find "$RPM_BUILD_ROOT" \! \( \
    -name '*.pyo' -o -name '*.pyc' -o -name '*.elc' -o -name '.packlist' \
    -o -name '*.src.rpm' \
    \) -type f -print0 | \
    xargs -0r "-P$NCPUS" -n16 grep -lF "$RPM_BUILD_ROOT" >>"$tmp" 2>&1

if test -s "$tmp"; then
    cat "$tmp"
    echo "Found '$RPM_BUILD_ROOT' in installed files; aborting"
    exit 1
fi
