#!/bin/bash

bashit="/bin/bash --rpm-requires"

# Make sure that this bash has the rpm-requires hack
$bashit < /dev/null 2>&1 > /dev/null || exit $?

prereqs="`cat | $bashit | sort | uniq | sed -e 's/^bash(//' -e 's/)$//' -e 's/^executable(//' -e 's/)$//'`"
[ -z "$prereqs" ] && exit 0

for prereq in $prereqs
do
    case $prereq in
    /*)	echo $prereq ;;
    *)	echo "`which $prereq`" ;;
    esac
done | sort | uniq
