#!/bin/sh

samples="
sexp-sample-a
sexp-sample-b
sexp-sample-c
"

expected=sexp-sample.exp

rc=0
for s in $samples
do
    ../sexp < $s > ${s}.out || rc=1
    diff -u ${s}.out $expected || rc=1
    rm -f ${s}.out
done

exit $rc
