#!/bin/sh

DBG=echo

rpm=${rpm:=rpm}
destdir="`pwd`"
destdir="`dirname $destdir`"

cp hello-1.0.tar.gz ../usr/src/redhat/SOURCES
zcat hello-1.0.tar.gz | tar xOf - \*.spec > ../usr/src/redhat/SPECS/hello.spec

${DBGX} $rpm -ba ../usr/src/redhat/SPECS/hello.spec 2>&1 | \
	sed -e "s,$destdir,,g" -e '/^make\[[0-9][0-9]*\]:/d' > $0.out

diff $0.out $0.exp || exit 1

