Entry count: 34

             CT  TAG                  TYPE               OFSET      COUNT
Entry      : 000 (100)(unknown)      STRING_ARRAY_TYPE  0xffffffff 00000001
       Data: 000 C
Entry      : 001 (1000)RPMTAG_NAME    STRING_TYPE        0xffffffff 00000001
       Data: 000 hello
Entry      : 002 (1001)RPMTAG_VERSION STRING_TYPE        0xffffffff 00000001
       Data: 000 1.0
Entry      : 003 (1002)RPMTAG_RELEASE STRING_TYPE        0xffffffff 00000001
       Data: 000 1
Entry      : 004 (1004)RPMTAG_SUMMARY I18N_STRING_TYPE   0xffffffff 00000001
       Data: 000 hello -- hello, world rpm
Entry      : 005 (1005)RPMTAG_DESCRIPTION I18N_STRING_TYPE   0xffffffff 00000001
       Data: 000 Simple rpm demonstration.
Entry      : 006 (1006)RPMTAG_BUILDTIME INT32_TYPE         0xffffffff 00000001
       Data: 000 0x362c9f02 (908893954)
Entry      : 007 (1007)RPMTAG_BUILDHOST STRING_TYPE        0xffffffff 00000001
       Data: 000 krusty.devel.redhat.com
Entry      : 008 (1009)RPMTAG_SIZE    INT32_TYPE         0xffffffff 00000001
       Data: 000 0x00007843 (30787)
Entry      : 009 (1014)RPMTAG_LICENSE STRING_TYPE        0xffffffff 00000001
       Data: 000 GPL
Entry      : 010 (1016)RPMTAG_GROUP   I18N_STRING_TYPE   0xffffffff 00000001
       Data: 000 Utilities
Entry      : 011 (1021)RPMTAG_OS      STRING_TYPE        0xffffffff 00000001
       Data: 000 Linux
Entry      : 012 (1022)RPMTAG_ARCH    STRING_TYPE        0xffffffff 00000001
       Data: 000 sparc
Entry      : 013 (1027)RPMTAG_FILENAMES STRING_ARRAY_TYPE  0xffffffff 00000001
       Data: 000 /usr/local/bin/hello
Entry      : 014 (1028)RPMTAG_FILESIZES INT32_TYPE         0xffffffff 00000001
       Data: 000 0x00007843 (30787)
Entry      : 015 (1030)RPMTAG_FILEMODES INT16_TYPE         0xffffffff 00000001
       Data: 000 0xffff81ed (-32275)
Entry      : 016 (1033)RPMTAG_FILERDEVS INT16_TYPE         0xffffffff 00000001
       Data: 000 0x0000 (0)
Entry      : 017 (1034)RPMTAG_FILEMTIMES INT32_TYPE         0xffffffff 00000001
       Data: 000 0x362c9efe (908893950)
Entry      : 018 (1035)RPMTAG_FILEMD5S STRING_ARRAY_TYPE  0xffffffff 00000001
       Data: 000 741e702cdf114c95a9e965fa8aa40864
Entry      : 019 (1036)RPMTAG_FILELINKTOS STRING_ARRAY_TYPE  0xffffffff 00000001
       Data: 000 
Entry      : 020 (1037)RPMTAG_FILEFLAGS INT32_TYPE         0xffffffff 00000001
       Data: 000 0x00000000 (0)
Entry      : 021 (1039)RPMTAG_FILEUSERNAME STRING_ARRAY_TYPE  0xffffffff 00000001
       Data: 000 root
Entry      : 022 (1040)RPMTAG_FILEGROUPNAME STRING_ARRAY_TYPE  0xffffffff 00000001
       Data: 000 root
Entry      : 023 (1044)RPMTAG_SOURCERPM STRING_TYPE        0xffffffff 00000001
       Data: 000 hello-1.0-1.src.rpm
Entry      : 024 (1045)RPMTAG_FILEVERIFYFLAGS INT32_TYPE         0xffffffff 00000001
       Data: 000 0xffffffff (-1)
Entry      : 025 (1046)RPMTAG_ARCHIVESIZE INT32_TYPE         0xffffffff 00000001
       Data: 000 0x00007944 (31044)
Entry      : 026 (1048)RPMTAG_REQUIREFLAGS INT32_TYPE         0xffffffff 00000002
       Data: 000 0x00000000 (0)
       Data: 001 0x00000000 (0)
Entry      : 027 (1049)RPMTAG_REQUIRENAME STRING_ARRAY_TYPE  0xffffffff 00000002
       Data: 000 ld-linux.so.2
       Data: 001 libc.so.6
Entry      : 028 (1050)RPMTAG_REQUIREVERSION STRING_ARRAY_TYPE  0xffffffff 00000002
       Data: 000 
       Data: 001 
Entry      : 029 (1064)RPMTAG_RPMVERSION STRING_TYPE        0xffffffff 00000001
       Data: 000 2.90
Entry      : 030 (1094)RPMTAG_COOKIE  STRING_TYPE        0xffffffff 00000001
       Data: 000 krusty.devel.redhat.com 908893954
Entry      : 031 (1095)RPMTAG_FILEDEVICES INT32_TYPE         0xffffffff 00000001
       Data: 000 0x00000804 (2052)
Entry      : 032 (1096)RPMTAG_FILEINODES INT32_TYPE         0xffffffff 00000001
       Data: 000 0x00010de6 (69094)
Entry      : 033 (1097)RPMTAG_FILELANGS STRING_ARRAY_TYPE  0xffffffff 00000001
       Data: 000 
