Entry count: 2

             CT  TAG                  TYPE               OFSET      COUNT
Entry      : 000 (1000)RPMTAG_NAME    INT32_TYPE         0xffffffff 00000001
       Data: 000 0x000041c3 (16835)
Entry      : 001 (1004)RPMTAG_SUMMARY BIN_TYPE           0xffffffff 00000016
       Data: 000 15 ffffffb1 ffffffad ffffffc7 03 ffffffb6 53 33 
       Data: 008 27 52 52 ffffffad fffffff7 1f ffffffb2 25 
