Name        : hello                       Distribution: RPM test suite.
Version     : 1.0                               Vendor: Red Hat Software
Release     : 1                             Build Date: Tue Mar  9 13:42:25 1999
Install date: Tue Mar  9 13:42:30 1999      Build Host: sparc9.test.redhat.com
Group       : Utilities                     Source RPM: hello-1.0-1.src.rpm
Size        : 31847                            License: GPL
Packager    : Red Hat Software <bugs@redhat.com>
URL         : http://www.redhat.com
Summary     : hello -- hello, world rpm
Description :
Simple rpm demonstration.
preinstall program: /bin/sh
postinstall program: /bin/sh
preuninstall program: /bin/sh
postuninstall program: /bin/sh
/home/devel/jbj/src/rpm/tests/hello-test/../usr/doc/hello-1.0
/home/devel/jbj/src/rpm/tests/hello-test/../usr/doc/hello-1.0/FAQ
/home/devel/jbj/src/rpm/tests/hello-test/../usr/local/bin/hello
