ARCHITECTURE AND OS:
build arch            : sparc
compatible build archs: sparc noarch
build os              : Linux
compatible build os's : Linux
install arch          : sparc
install os            : Linux
compatible archs      : sparc noarch
compatible os's       : Linux
RPMRC VALUES:
builddir              : /usr/src/redhat/BUILD
buildroot             : (not set)
buildshell            : /bin/sh
bzip2bin              : /usr/bin/bzip2
dbpath                : /var/lib/rpm
defaultdocdir         : /usr/doc
distribution          : (not set)
excludedocs           : (not set)
fixperms              : a+rX,g-w,o-w
ftpport               : (not set)
ftpproxy              : (not set)
gzipbin               : /bin/gzip
instchangelog         : 5
langpatt              : (not set)
messagelevel          : (not set)
netsharedpath         : (not set)
optflags              : -O2
packager              : (not set)
pgp_name              : (not set)
pgp_path              : (not set)
provides              : (not set)
require_distribution  : (not set)
require_icon          : (not set)
require_vendor        : (not set)
rpmdir                : /usr/src/redhat/RPMS
rpmfilename           : %{ARCH}/%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}.rpm
signature             : none
sourcedir             : /usr/src/redhat/SOURCES
specdir               : /usr/src/redhat/SPECS
srcrpmdir             : /usr/src/redhat/SRPMS
timecheck             : (not set)
tmppath               : /var/tmp
topdir                : /usr/src/redhat
vendor                : (not set)
