ARCHITECTURE AND OS:
build arch            : sparc
compatible build archs: sparc noarch
build os              : Linux
compatible build os's : linux
install arch          : sparc
install os            : Linux
compatible archs      : sparc noarch
compatible os's       : linux

RPMRC VALUES:
builddir              : /usr/src/redhat/BUILD
buildshell            : /bin/sh
bzip2bin              : /usr/bin/bzip2
dbpath                : /var/lib/rpm
defaultdocdir         : /usr/doc
fixperms              : a+rX,g-w,o-w
gzipbin               : /bin/gzip
instchangelog         : 5
macrofiles            : /usr/lib/rpm/macros
optflags              : -O2
rpmdir                : /usr/src/redhat/RPMS
rpmfilename           : %{ARCH}/%{NAME}-%{VERSION}-%{RELEASE}.%{ARCH}.rpm
signature             : none
sourcedir             : /usr/src/redhat/SOURCES
specdir               : /usr/src/redhat/SPECS
srcrpmdir             : /usr/src/redhat/SRPMS
tmppath               : /var/tmp
topdir                : /usr/src/redhat
