Executing: %prep
+ umask 022
+ cd /usr/src/redhat/BUILD
+ cd /usr/src/redhat/BUILD
+ rm -rf hello-1.0
+ /bin/gzip -dc /usr/src/redhat/SOURCES/hello-1.0.tar.gz
+ tar -xf -
+ STATUS=0
+ [ 0 -ne 0 ]
+ cd hello-1.0
+ chmod -R a+rX,g-w,o-w .
+ exit 0
Executing: %build
+ umask 022
+ cd /usr/src/redhat/BUILD
+ cd hello-1.0
+ make
make[2]: Entering directory `/usr/src/redhat/BUILD/hello-1.0'
make[2]: Nothing to be done for `all'.
make[2]: Leaving directory `/usr/src/redhat/BUILD/hello-1.0'
+ exit 0
Executing: %install
+ umask 022
+ cd /usr/src/redhat/BUILD
+ cd hello-1.0
+ rm -rf /var/tmp/hello-root
+ mkdir -p /var/tmp/hello-root/usr/local/bin
+ make DESTDIR=/var/tmp/hello-root install
make[2]: Entering directory `/usr/src/redhat/BUILD/hello-1.0'
install -m 0755 hello /var/tmp/hello-root/usr/local/bin
make[2]: Leaving directory `/usr/src/redhat/BUILD/hello-1.0'
+ exit 0
Processing files: hello
Finding provides...
Finding requires...
Requires: ld-linux.so.2 libc.so.6
Wrote: /usr/src/redhat/SRPMS/hello-1.0-1.src.rpm
Wrote: /usr/src/redhat/RPMS/sparc/hello-1.0-1.sparc.rpm
Executing: %clean
+ umask 022
+ cd /usr/src/redhat/BUILD
+ cd hello-1.0
+ rm -rf /var/tmp/hello-root
+ exit 0
