#!/bin/sh

DBG=echo

rpm=${rpm:=rpm}
destdir="`pwd`"
destdir="`dirname $destdir`"

${DBGX} $rpm --initdb
${DBGX} $rpm --showrc

#${DBGX} $rpm -ta hello-1.0-tar.gz

cp hello-1.0.tar.gz ../usr/src/redhat/SOURCES
zcat hello-1.0.tar.gz | tar xOf - \*.spec > ../usr/src/redhat/SPECS/hello.spec
${DBGX} $rpm -ba ../usr/src/redhat/SPECS/hello.spec 2>&1 | sed -e "s,$destdir,," > test0.out

exit 0
