.TH "RPM-SYSTEMD-INHIBIT" "8" "14 Apr 2016" "Red Hat, Inc."
.SH NAME
rpm-plugin-systemd-inhibit \- Plugin for the RPM Package Manager

.SH Description

This plugin for RPM prevents the system to enter shutdown, sleep or idle
mode while there is a rpm transaction running to prevent system corruption
that can occur if the transaction is interrupted by a reboot.

This is achieved by using the inhibit DBUS interface of systemd. The call is
roughly equivalent to executing

\fBsystemd-inhibit --mode=block --what=idle:sleep:shutdown --who=RPM --why="Transaction running"\fR

See \fBsystemd-inhibit\fR(1) for the details of this mechanism.

It is strongly advised to have the plugin installed on all systemd
based systems.

.SH Prerequisites

For the plugin to work systemd has to be used as init system and
though the DBUS system bus must be available. If the plugin cannot access the
interface it gives a warning but does not stop the transaction.

.SH Configuration

There are currently no options for this plugin in particular. See
.BR rpm-plugins (8)
on how to control plugins in general.

.SH SEE ALSO
.IR systemd-inhibit (1)
.IR rpm (8)
.IR rpm-plugins (8)
