.TH "RPMDB" "8" "29 June 2010" "Red Hat, Inc"
.SH NAME
rpmdb \- RPM Database Tool
.SH SYNOPSIS

\fBrpm\fR {\fB--initdb|--rebuilddb\fR}

.SH "DESCRIPTION"
The general form of an rpm rebuild database command is 
.PP

\fBrpm\fR {\fB--initdb|--rebuilddb\fR} [\fB-v\fR] [\fB--dbpath \fIDIRECTORY\fB\fR] [\fB--root \fIDIRECTORY\fB\fR]

.PP
Use \fB--initdb\fR to create a new database if one doesn't already exist
(existing database is not overwritten), use
\fB--rebuilddb\fR to rebuild the database indices from
the installed package headers.
.PP

.SH "SEE ALSO"

.nf
\fBpopt\fR(3),
\fBrpm\fR(8),
\fBrpmkeys\fR(8),
\fBrpmsign\fR(8),
\fBrpm2cpio\fR(8),
\fBrpmbuild\fR(8),
\fBrpmspec\fR(8),
.fi

\fBrpm --help\fR - as rpm supports customizing the options via popt aliases 
it's impossible to guarantee that what's described in the manual matches 
what's available.


\fBhttp://www.rpm.org/ <URL:http://www.rpm.org/>
\fR
.SH "AUTHORS"

.nf
Marc Ewing <marc@redhat.com>
Jeff Johnson <jbj@redhat.com>
Erik Troan <ewt@redhat.com>
Panu Matilainen <pmatilai@redhat.com>
.fi

