FROM registry.fedoraproject.org/fedora:41

RUN dnf install -y \
    gcc \
    gcc-c++ \
    glibc-langpack-en \
    make \
    ruby-devel

COPY Gemfile .
RUN bundle install

ENV LC_ALL en_US.UTF-8
EXPOSE 4000
WORKDIR /srv

ENTRYPOINT ["bundle", "exec", "jekyll"]
