.TH "RPM-SYSLOG" "8" "14 Apr 2016" "Red Hat, Inc."
.SH NAME
rpm-plugin-syslog \- Syslog plugin for the RPM Package Manager

.SH Description

The plugin writes basic information about rpm transactions to the syslog - like transactions run and packages installed or removed.

.SH Configuration

There are currently no options for this plugin in particular. See
.BR rpm-plugins (8)
on how to control plugins in general.

.SH SEE ALSO
.IR rpm (8)
.IR rpm-plugins (8)
