.\" rpm - Red Hat Package Manager
.TH rpm 8 "1996鰍 7杉 15析" "傾球媒 社覗闘裾嬢" "傾球媒 軒勘什"
.SH 戚硯
rpm \- 傾球媒 鳶徹走 淫軒切
.SH 鯵推
\fBrpm\fP [辛芝級] 
.SH 竺誤
\fBrpm\fP 精 悪径廃 \fI鳶徹走 淫軒切\fP 稽辞 
唖唖税 社覗闘裾嬢 鳶徹走研 幻級壱 竺帖馬壱 霜庚馬壱 伊装馬壱 飴重馬悟
薦暗拝 呪 赤陥.
\fI鳶徹走\fP 空  竺帖拝 鉢析級引 戚硯, 獄穿, 竺誤 去聖
匂敗馬澗 鳶徹走 舛左研 走観 煽舌 鉢析戚陥.

奄沙旋昔 7 亜走 疑拙 乞球亜 赤生悟 唖唖 陥献 辛芝級聖 握澗陥.
\fI竺帖\fP, \fI霜庚\fP,
\fI伊装\fP, \fI辞誤 溌昔\fP, \fI薦暗\fP, \fI薦拙\fP,
益軒壱 \fI汽戚斗今戚什 仙闇竺\fP 戚 郊稽 益依戚陥.

竺帖 乞球:
.br
.I "\fB    rpm \-i [竺帖辛芝] <鳶徹走 鉢析>+\fP"
.br
霜庚 乞球:
.br
.I "\fB    rpm \-q [霜庚辛芝]\fP"
.br
伊装 乞球:
.br
.I "\fB    rpm \-V|\-y|\-\-verify [伊装辛芝]\fP"
.br
辞誤 溌昔 乞球:
.br
.I "\fB    rpm \-\-checksig <鳶徹走鉢析>+\fP"
.br
薦暗 乞球:
.br
.I "\fB    rpm \-e <鳶徹走誤>+\fP"
.br
薦拙 乞球:
.br
.I "\fB    rpm \-b\fIO\fB [薦拙辛芝] <鳶徹走什薙>+\fP"
.br

.SH 析鋼旋 辛芝
陥製 辛芝級精 唖奄 陥献 乞球拭辞亀 紫遂亜管馬陥.
.IP "\fB\-vv\fP"
焼爽 切室馬惟 巨獄焔 舛左研 窒径廃陥.
.IP "\fB\-\-keep\-temps\fP"
績獣 鉢析聖 走酔走 省澗陥. (/tmp/rpm\-*). rpm 聖 巨獄焔拝 凶幻
爽稽 紫遂廃陥.
.IP "\fB\-\-quiet\fP"
置企廃 窒径聖 切薦馬悟 神稽走 拭君 五室走幻 窒径廃陥.
.IP "\fB\-\-help\fP"
岨 希 延 紫遂狛 竺誤辞研 窒径廃陥.
.IP "\fB\-\-version\fP"
紫遂 掻昔 rpm 税 獄穿聖 廃 匝稽 妊獣廃陥.
.IP "\fB\-\-rcfile <鉢析>\fP"
\fB/etc/rpmrc\fP 暁澗 \fB$HOME/.rpmrc\fP 聖 紫遂馬走 省壱
\fB<file>\fP 聖 紫遂馬亀系 廃陥.
.IP "\fB\-\-root <dir>\fP"
乞窮 疑拙拭 企馬食 置雌是 巨刑塘軒研 爽嬢遭 巨刑塘軒稽 竺舛馬壱 拙穣廃陥.
森研 級嬢 竺帖獣 爽嬢遭 巨刑塘軒研 / 虞壱 持唖馬壱 益依聖 奄層生稽
竺帖背蟹娃陥.

.SH 竺帖 辛芝
rpm 竺帖 誤敬税 析鋼旋昔 莫殿澗 陥製引 旭陥.
.PP
	\fBrpm \-i [竺帖辛芝級] <鳶徹走鉢析>+\fP
.PP
.IP "\fB\-\-force\fP"
\-\-replacepkgs, \-\-replacefiles, \-\-oldpackage 研 乞砧 紫遂廃 依引
旭陥.
.IP "\fB\-h, \-\-hash\fP"
鳶徹走研 熱 凶 背習原滴(#)研 妊獣廃陥. 恥 姐呪澗 50 鯵戚陥.
岨 希 蟹精 窒径聖 是背辞澗 \fB\-v\fP 研 敗臆 紫遂馬虞.
.IP "\fB\-\-oldpackage\fP"
歯稽錘 鳶徹走研 走酔壱 希 森穿 鳶徹走稽 嘘端拝 凶 紫遂廃陥.
.IP "\fB\-\-percent\fP"
鳶徹走 鉢析聖 熱 凶 遁湿闘 妊獣研 廃陥. 陥献 亀姥稽採斗 rpm 聖 戚遂拝 凶
紫遂拝 鯉旋生稽 幻級嬢然陥.
.IP "\fB\-\-replacefiles\fP"
戚耕 竺帖吉 陥献 鳶徹走税 鉢析聖 気嬢床檎辞虞亀 鳶徹走研 悪薦稽 竺帖廃陥.
.IP "\fB\-\-replacepkgs\fP"
鳶徹走亜 戚耕 竺帖鞠嬢 赤陥 馬希虞亀 陥獣 竺帖廃陥.
.IP "\fB\-\-root \fI<巨刑塘軒>\fP"
\fI<巨刑塘軒>\fP研 欠闘稽 馬澗 獣什奴拭 竺帖研 呪楳廃陥.
汽戚斗今戚什澗 \fI<巨刑塘軒>\fP 購拭辞 飴重鞠壱 \fIpre\fP 暁澗 \fIpost\fP
什滴験闘澗 \fI<巨刑塘軒>\fP稽 chroot() 廃 板 叔楳喫聖 税耕廃陥.
.IP "\fB\-\-noscripts\fP"
preinstall, postinstall 什滴験闘研 叔楳馬走 省澗陥.
.IP "\fB\-\-excludedocs\fP"
庚辞虞壱 妊獣鞠嬢 赤澗 鉢析(固凪戚走人 texinfo 庚辞)精 竺帖馬走 省澗陥.
.IP "\fB\-\-includedocs\fP"
庚辞 鉢析聖 匂敗廃陥. 戚 辛芝精 rpmrc 鉢析拭 \fIexcludedocs: 1\fP 戚虞澗
依戚 誤獣鞠嬢 赤聖 凶幻 琶推馬陥.
.IP "\fB\-\-nodeps\fP"
鳶徹走研 竺帖馬奄 穿拭 税糎失聖 伊紫馬走 省澗陥.
.IP "\fB\-\-test\fP"
鳶徹走研 叔薦稽 竺帖馬走澗 省壱 中宜 紫牌戚 赤澗走 繊伊馬壱 左壱廃陥.
.IP "\fB\-U, \-\-upgrade\fP"
薄仙 竺帖鞠嬢 赤澗 鳶徹走研 歯稽錘 獄穿税 RPM生稽 穣益傾戚球馬虞.
昔什島引 旭走幻 森穿 獄穿税 依戚 切疑生稽 走趨遭陥澗 依戚 陥牽陥.



.SH 霜庚 辛芝
rpm 霜庚 辛芝税 析鋼旋昔 莫縦精 陥製引 旭陥.
.PP
	\fBrpm \-q [霜庚辛芝]\fP
.PP
食君歳精 鳶徹走 舛左亜 妊獣吃 莫縦聖 衣舛背爽嬢醤 廃陥.
\fB\-\-queryformat\fP 辛芝 及拭 莫縦 庚切伸聖 旋嬢爽檎 吉陥.

霜庚 莫縦精 妊層 \fBprintf(3)\fP 莫縦聖 鉦娃 痕莫廃 依戚陥.
莫縦精 舛旋 庚切伸引( 鯵楳庚切, 吐, 益軒壱 陥献 働呪庚切拭
企廃 妊層 C 庚切 戚什追戚覗 妊奄) \fBprintf(3)\fP 莫縦走舛切稽 姥失鞠嬢
赤陥.
\fBrpm\fP精 戚耕 窒径 莫殿研 硝壱 赤生糠稽 展脊 走舛切澗 持繰馬壱
\fB{}\fP 庚切稽 広嬢辞 伯希 殿益税 戚硯生稽 郊荷嬢 爽嬢醤 廃陥.
殿益誤 掻 \fBRPMTAG_\fP 採歳精 持繰背醤 馬悟 殿益誤 蒋拭澗 \fB\-\fP 庚切研
旋嬢爽嬢醤 廃陥.

森研 級嬢 霜庚 企雌 鳶徹走税 戚硯幻 窒径馬壱切 馬澗 井酔 食君歳精 
\fB%{NAME}\fP 聖 莫縦 庚切伸稽 紫遂背醤 廃陥. 鳶徹走誤引 壕匂毒 舛左研
砧 鯵税 町軍生稽 妊獣馬壱切 拝 凶澗 \fB%\-30{NAME}%{DISTRIBUTION}\fP 虞壱
旋澗陥.

\fBrpm\fP 精 \fB\-\-querytags\fP 辛芝聖 爽檎 昔縦馬壱 赤澗 乞窮 殿益税
鯉系聖 左食層陥.

霜庚 辛芝拭澗 2 亜走 室闘亜 赤陥: 鳶徹走 識澱引 舛左 識澱

鳶徹走 識澱 辛芝:
.br
.IP "\fB\fI<鳶徹走誤>\fP"
\fB\fI<package_name>\fP虞澗 戚硯税 鳶徹走拭 企廃 霜庚研 呪楳廃陥.
.IP "\fB\-a\fP"
乞窮 鳶徹走拭 企馬食 霜庚研 呪楳廃陥.
.IP "\fB\-whatrequires \fI<奄管>\fP"
薦企稽 拙疑馬奄 是背辞澗 \fI<奄管>\fP 聖 琶推稽 馬澗 乞窮 鳶徹走拭 企馬食
霜庚聖 呪楳廃陥.
.IP "\fB\-whatprovides \fI<亜雌>\fP"
\fI<virtual>\fP 奄管聖 薦因馬澗 乞窮 鳶徹走拭 企馬食 霜庚聖 呪楳廃陥.
.IP "\fB\-f \fI<鉢析>\fP"
\fI<鉢析>\fP研 匂敗馬澗 鳶徹走拭 企馬食 霜庚聖 呪楳廃陥.
.IP "\fB\-F\fP"
\fB\-f\fP 人 旭走幻 鉢析誤聖 妊層 脊径拭辞 石澗陥.
.IP "\fB\-p \fI<鳶徹走鉢析>\fP"
竺帖吉 暁澗 竺帖鞠走 省精 \fI<鳶徹走鉢析>\fP 拭 企馬食 霜庚聖 呪楳廃陥.
.IP "\fB\-P\fP"
\fB\-p\fP 人 旭走幻 鳶徹走 鉢析誤聖 妊層 脊径拭辞 石澗陥.

.P
舛左 識澱 辛芝:
.br
.IP "\fB\-i\fP"
鳶徹走 戚硯, 獄穿, 竺誤 去税 舛左研 窒径廃陥.
幻鉦 \fB\-\-queryformat\fP 戚 爽嬢閃 赤陥檎 益依聖 戚遂馬食 窒径廃陥.
.IP "\fB\-R\fP"
薄仙 鳶徹走走亜 税糎馬壱 赤澗 鳶徹走 鯉系聖 左食層陥.
(\fB\-\-requires\fP 引 旭製)
.IP "\fB\-\-provides\fP"
鳶徹走亜 薦因馬澗 奄管聖 左食層陥.
.IP "\fB\-l\fP"
鳶徹走 照税 鉢析聖 左食層陥.
.IP "\fB\-s\fP"
鳶徹走 照拭 窮 鉢析税 \fI雌殿\fP研 左食層陥.(\fB\-l\fP精 匂敗)
唖 鉢析税 雌殿澗 \fInormal\fP(舛雌), \fInot installed\fP(竺帖鞠走 省製),
\fIreplaced\f(陥献 依生稽 嘘端喫)税 葵聖 握澗陥.
.IP "\fB\-d\fP"
庚辞 鉢析幻 左食層陥.(\fB\-l\fP精 匂敗)
.IP "\fB\-c\fP"
竺舛 鉢析幻 左食層陥.(\fB\-l\fP精 匂敗)
.IP "\fB\-\-scripts\fP"
竺帖, 薦暗 引舛拭 紫遂鞠澗 秋 什滴験闘亜 赤陥檎 益 鎧遂聖 窒径廃陥.
.IP "\fB\-\-dump\fP"
陥製引 旭精 鉢析 舛左研 棋覗廃陥: 井稽 滴奄 呪舛析, MD5 端滴雫, 乞球,
社政切, 益血, 竺舛 鉢析 食採, 庚辞 鉢析 食採, rdev, 宿瑳遣 元滴 食採.
置社廃 \fB\-l\fP, \fB\-c\fP, \fB\-d\fP 戚級 辛芝 掻 馬蟹亜 紫遂鞠嬢醤
廃陥.

.SH 伊装 辛芝
rpm 伊装 辛芝税 析鋼旋昔 莫殿澗 陥製引 旭陥.
.PP
	\fBrpm \-V|\-y|\-\-verify [伊装辛芝]\fP
.PP
竺帖鞠嬢 赤澗 鉢析級拭 企馬食 rpm 汽戚斗今戚什拭 煽舌吉 鎧遂引 神軒走確
鳶徹走税 鎧遂聖 搾嘘廃陥. 伊装 鎧遂精 滴奄, MD5 端滴雫, 遁耕芝, 展脊, 社政切,
益血 去戚陥. 託戚繊戚 降胃鞠檎 窒径廃陥. 鳶徹走 走獣 辛芝精 鳶徹走 霜庚
辛芝拭辞人 旭陥.

窒径 莫縦精 8 切税 庚切伸戚陥. "\fBc\fP"精 竺舛 鉢析聖 税耕馬悟 益軒壱
鉢析誤戚 蟹展貝陥. 唖唖税 8 鯵 庚切澗 RPM 汽戚斗今戚什拭 煽舌吉 紗失引 搾嘘廃
衣引研 蟹展浬陥. "." (杷軒嬢球) 庚切澗 戚雌蒸製聖 蟹展浬陥. 搾嘘 衣引 庚薦繊戚
降胃鞠檎 陥製引 旭精 庚切亜 蟹展貝陥.

.IP "\fB5\fP"
MD5 端滴雫
.IP "\fBS\fP"
鉢析 滴奄
.IP "\fBL\fP"
宿瑳遣 元滴
.IP "\fBT\fP"
飴重析
.IP "\fBD\fP"
舌帖
.IP "\fBU\fP"
紫遂切
.IP "\fBG\fP"
益血
.IP "\fBM\fP"
遁耕芝引 鉢析 展脊聖 匂敗廃 乞球

.SH 辞誤 溌昔
rpm 辞誤 溌昔 誤敬精 陥製引 旭陥.
.PP
	\fBrpm \-\-checksig <鳶徹走鉢析>+\fP
.PP
鳶徹走税 神軒走確 食採研 亜形鎧奄 是馬食 鳶徹走 照拭 窮 PGP 辞誤聖 繊伊廃陥.
PGP 竺舛 舛左澗 /etc/rpmrc 拭辞 石嬢紳陥.
室採紫牌精 "PGP 辞誤" 悉芝聖 左奄 郊空陥.

.SH 薦暗 辛芝
rpm 薦暗 誤敬税 析鋼旋昔 莫殿澗 陥製引 旭陥.
.PP
	\fB    rpm \-e <鳶徹走鉢析>+\fP
.PP
.IP "\fB\-\-noscripts\fP"
preunistall, postuninstall 什滴験闘研 叔楳馬走 省澗陥.
.IP "\fB\-\-nodeps\fP"
鳶徹走 薦暗獣 税糎失聖 伊紫馬走 省澗陥.
.IP "\fB\-\-test\fP"
叔薦稽 鳶徹走研 薦暗馬澗 依精 焼艦壱 砺什闘背沙陥.
\fB\-vv\fP 辛芝.

.SH 薦拙 辛芝
rpm 薦拙 誤敬税 析鋼旋 莫縦精 陥製引 旭陥.
.PP
    \fBrpm \-b\fIO\fP [薦拙辛芝] <鳶徹走 什薙>+\fP
.PP
\fB\-b\fIO\fR 精 薦拙 舘域人 薦拙拝 鳶徹走研 蟹展鎧澗 依生稽辞 陥製 掻
馬蟹税 葵聖 握澗陥:

.IP "\fB\-bp\fP"
什薙 鉢析税 "%prep" 舘域研 叔楳廃陥. 左搭 社什研 熱壱 鳶帖研 亜馬澗 拙穣戚陥.
.IP "\fB\-bl\fP"
"鯉系 繊伊"聖 廃陥. "%files" 悉芝精 溌舌 古滴稽戚陥. 戚 鉢析級戚 糎仙馬澗走
食採研 硝焼沙陥.
.IP "\fB\-bc\fP"
"%build" 舘域研 呪楳廃陥.( prep 舘域研 廃 板 ) 
左搭 make 拭 背雁馬澗 析聖 背浬陥.
.IP "\fB\-bi\fP"
"%install" 舘域研 呪楳廃陥.( prep, build 舘域研 暗庁 板 )
左搭 make install 拭 背雁馬澗 析聖 廃陥.
.IP "\fB\-bb\fP"
郊戚格軒 鳶徹走研 幻窮陥.( prep, build, install 舘域研 呪楳廃 板 )
.IP "\fB\-ba\fP"
郊戚格軒人 社什 鳶徹走研 幻窮陥.( prep, build, install 舘域研 呪楳廃 板 )
.PP
陥製 辛芝亀 紫遂亜管馬陥:
.IP "\fB\-\-short\-circuit\fP"
掻娃 舘域研 暗帖走 省壱 走舛廃 舘域稽 送羨 戚疑廃陥.
\fB\-bc\fP 人 \fB\-bi\fP馬壱幻 承 呪 赤陥.
.IP "\fB\-\-timecheck\fP"
"獣娃繊伊"聖 0 ( 災亜管 )生稽 竺舛廃陥. 戚 葵精 rpmrc 拭辞 "timecheck:" 稽
竺舛拝 呪 赤陥. 獣娃繊伊葵精 段稽 妊獣鞠澗汽 鉢析戚 鳶徹臓鞠澗 杏軒澗 置企
獣娃聖 舛廃陥. 獣娃聖 段引馬澗 鉢析級拭 企馬食 井壱 五獣走亜 窒径吉陥. 
.IP "\fB\-\-clean\fP"
鳶徹走研 幻窮 板 build 巨刑塘軒研 走錘陥.
.IP "\fB\-\-test\fP"
嬢彊廃 build 舘域研 暗帖走 省澗陥.
什薙 鉢析聖 砺什闘拝 凶 政遂馬陥.
.IP "\fB\-\-sign\fP"
鳶徹走 照拭 PGP 辞誤聖 隔澗陥. 鳶徹走研 刊亜 幻級醸澗走 溌昔拝 呪 赤陥.
/etc/rpmrc 拭 企廃 竺誤精 PGP 辞誤 悉芝聖 石嬢左虞.

.SH 仙薦拙, 仙陳督析 辛芝

舘 砧 亜走幻 赤聖 屍戚陥:

.I "\fBrpm \-\-recompile <社什鳶徹走鉢析>+\fP"

.I "\fBrpm \-\-rebuild <社什鳶徹走鉢析>+\fP"

rpm 精 爽嬢遭 社什 鳶徹走研 竺帖馬壱 prep, 陳督析, 竺帖研 背層陥.
\fB\-\-rebuild\fP澗 歯稽錘 郊戚格軒 鳶徹走亀 幻級嬢層陥.
薦拙聖 原帖檎 build 巨刑塘軒澗 \fB\-\-clean\fP 辛芝拭辞人 原濁亜走稽
走趨遭陥. 鳶徹走稽採斗 蟹紳 社什人 什薙鉢析精 肢薦吉陥.

.SH 奄糎税 RPM拭 辞誤馬奄

.I "\fBrpm \-\-resign <郊戚格軒鳶徹走鉢析>+\fP"

鳶徹走 鉢析拭 歯稽錘 辞誤聖 廃陥. 奄糎税 辞誤精 肢薦吉陥.

.SH PGP 辞誤

辞誤 奄管聖 紫遂馬奄 是背辞澗 PGP 研 紫遂拝 呪 赤嬢醤 廃陥.( 食君歳税 鳶什
杏鍵 巨刑塘軒 竺帖鞠嬢 赤嬢醤 廃陥 ) 益軒壱 RPM 因鯵徹研 匂敗馬澗 因鯵徹 元聖
達聖 呪 赤嬢醤 廃陥. 奄沙旋生稽 RPM精 PGPPATH拭辞 走獣馬澗 PGP 奄沙 竺舛聖
紫遂廃陥. PGP亜 奄沙旋生稽 紫遂馬澗 徹元聖 握壱 赤走 省聖 凶澗 /etc/rpmrc
鉢析拭 陥製引 旭戚 竺舛背砧嬢醤 廃陥.

.IP "\fBpgp_path\fP"
/usr/lib/rpm 企重 床析 井稽誤. 食君歳税 徹元聖 匂敗背醤 廃陥.
.PP

食君歳戚 幻窮 鳶徹走拭 辞誤聖 馬形檎, 食君歳精 切重税 因鯵徹人 搾腔徹 廃 瞬聖
幻級嬢砧嬢醤 廃陥.( PGP 古敢杖 凧壱 )
/etc/rpmrc 拭 旋澗 依 源壱亀 陥製 紫牌聖 蓄亜背醤 廃陥:

.IP "\fBsignature\fP"
辞誤 政莫. 薄仙稽辞澗 pgp 幻 走据吉陥.
.IP "\fBpgp_name\fP"
食君歳税 鳶徹走拭 辞誤拝 user 誤聖 旋澗陥.
.PP

鳶徹走 薦拙獣 \-\-sign 辛芝聖 蓄亜廃陥.
食君歳税 脊径聖 閤壱 蟹檎 鳶徹走亜 幻級嬢走壱 疑獣拭 辞誤吉陥.

.SH 汽戚斗今戚什 仙持失 辛芝

rpm 汽戚斗今戚什研 陥獣 幻球澗 誤敬精 陥製引 旭陥.
.PP
	\fBrpm \-\-rebuilddb\fP
.PP

戚 乞球人 紫遂鞠澗 辛芝生稽澗 \fB-\-dbpath\fP 人 \fB-\-root\fP 却 屍戚陥.

.SH 淫恵 鉢析
.nf
/etc/rpmrc
~/.rpmrc
/var/lib/rpm/packages
/var/lib/rpm/pathidx
/var/lib/rpm/nameidx
/tmp/rpm*
.fi
.El
.SH 凧壱
.IR glint (8) ,
.IR rpm2cpio (8) ,
.B http://www.redhat.com/rpm
.nf
.SH 煽切
.nf
Marc Ewing <marc@redhat.com>
Erik Troan <ewt@redhat.com>
.fi
.SH 腰蝕切
.br
戚 幻 遂
.B <geoman@nownuri.nowcom.co.kr>
.br
.B "         <freeyong@soback.kornet.nm.kr>"

