.\" rpm2cpio - Converts Red Hat Package (RPM) to cpio archive
.TH rpm 8 "1995鰍 9杉 15析" "傾球媒 社覗闘裾嬢" "傾球媒 雌遂 軒勘什"
.SH 戚硯
rpm2cpio \- 傾球媒 (RPM) 鳶徹走研 cpio 鉢析稽 痕発
.SH 鯵推
\fBrpm2cpio\fP [filename] 
.SH 竺誤
\fBrpm2cpio\fP 澗 .rpm 鉢析誤聖 馬蟹 閤焼級食辞 妊層窒径生稽 cpio 煽舌鉢析聖
窒径廃陥. 幻鉦 焼巷訓 穿含昔呪亜 蒸陥檎 妊層脊径生稽採斗 rpm 鉢析聖
閤焼級昔陥.

.br
.I "\fBrpm2cpio rpm-1.1-1.i386.rpm\fP"
.br
.I "\fBrpm2cpio < glint-1.0-1.i386.rpm\fP"

.SH 凧壱
.IR glint (8) ,
.IR rpm (8)
.SH 煽切
.nf
Erik Troan <ewt@redhat.com>
.fi

.SH 腰蝕切
.br
戚 幻 遂
.B <geoman@nownuri.nowcom.co.kr>
.br
.B "         <freeyong@soback.kornet.nm.kr>"

